export const FeatureKeys = <const>{
    Ammunition:      "Ammunition",
    Armor:           "Armor",
    Builder:         "Builder",
    CharacterStatus: "CharacterStatus",
    Checklist:       "Checklist",
    Core:            "Core",
    Equipment:       "Equipment",
    ImportExport:    "ImportExport",
    LevelUp:         "LevelUp",
    QuickItems:      "QuickItems",
    Router:          "Router",
    Routing:         "Routing",
    Spells:          "Spells",
    StartingClass:   "StartingClass",
    Talismans:       "Talismans",
    Weapons:         "Weapons",
}
