export * from "./AboutFooter"
export * from "./ArmorFooter"
export * from "./BuilderFooter"
export * from "./EquipmentFooter"
export * from "./NoFooter"
export * from "./TalismanFooter"
export * from "./WeaponFooter"
