class CreateWeaponStats < ActiveRecord::Migration[7.0]
  def change()
    create_table(:weapon_stats) do |t|

      t.string(:name, null: false, index: { unique: true })

      t.integer(:attack_element_correct_param_id, null: false, index: true)
      t.integer(:weapon_id,                       null: false, index: true)
      t.integer(:weapon_affinity_id,              null: false, index: true)

      t.decimal(:attack_physical__0,      null: false)
      t.decimal(:attack_physical__1,      null: false)
      t.decimal(:attack_physical__2,      null: false)
      t.decimal(:attack_physical__3,      null: false)
      t.decimal(:attack_physical__4,      null: false)
      t.decimal(:attack_physical__5,      null: false)
      t.decimal(:attack_physical__6,      null: false)
      t.decimal(:attack_physical__7,      null: false)
      t.decimal(:attack_physical__8,      null: false)
      t.decimal(:attack_physical__9,      null: false)
      t.decimal(:attack_physical__10,     null: false)
      t.decimal(:attack_physical__11,     null: false)
      t.decimal(:attack_physical__12,     null: false)
      t.decimal(:attack_physical__13,     null: false)
      t.decimal(:attack_physical__14,     null: false)
      t.decimal(:attack_physical__15,     null: false)
      t.decimal(:attack_physical__16,     null: false)
      t.decimal(:attack_physical__17,     null: false)
      t.decimal(:attack_physical__18,     null: false)
      t.decimal(:attack_physical__19,     null: false)
      t.decimal(:attack_physical__20,     null: false)
      t.decimal(:attack_physical__21,     null: false)
      t.decimal(:attack_physical__22,     null: false)
      t.decimal(:attack_physical__23,     null: false)
      t.decimal(:attack_physical__24,     null: false)
      t.decimal(:attack_physical__25,     null: false)
      t.decimal(:attack_magic__0,         null: false)
      t.decimal(:attack_magic__1,         null: false)
      t.decimal(:attack_magic__2,         null: false)
      t.decimal(:attack_magic__3,         null: false)
      t.decimal(:attack_magic__4,         null: false)
      t.decimal(:attack_magic__5,         null: false)
      t.decimal(:attack_magic__6,         null: false)
      t.decimal(:attack_magic__7,         null: false)
      t.decimal(:attack_magic__8,         null: false)
      t.decimal(:attack_magic__9,         null: false)
      t.decimal(:attack_magic__10,        null: false)
      t.decimal(:attack_magic__11,        null: false)
      t.decimal(:attack_magic__12,        null: false)
      t.decimal(:attack_magic__13,        null: false)
      t.decimal(:attack_magic__14,        null: false)
      t.decimal(:attack_magic__15,        null: false)
      t.decimal(:attack_magic__16,        null: false)
      t.decimal(:attack_magic__17,        null: false)
      t.decimal(:attack_magic__18,        null: false)
      t.decimal(:attack_magic__19,        null: false)
      t.decimal(:attack_magic__20,        null: false)
      t.decimal(:attack_magic__21,        null: false)
      t.decimal(:attack_magic__22,        null: false)
      t.decimal(:attack_magic__23,        null: false)
      t.decimal(:attack_magic__24,        null: false)
      t.decimal(:attack_magic__25,        null: false)
      t.decimal(:attack_fire__0,          null: false)
      t.decimal(:attack_fire__1,          null: false)
      t.decimal(:attack_fire__2,          null: false)
      t.decimal(:attack_fire__3,          null: false)
      t.decimal(:attack_fire__4,          null: false)
      t.decimal(:attack_fire__5,          null: false)
      t.decimal(:attack_fire__6,          null: false)
      t.decimal(:attack_fire__7,          null: false)
      t.decimal(:attack_fire__8,          null: false)
      t.decimal(:attack_fire__9,          null: false)
      t.decimal(:attack_fire__10,         null: false)
      t.decimal(:attack_fire__11,         null: false)
      t.decimal(:attack_fire__12,         null: false)
      t.decimal(:attack_fire__13,         null: false)
      t.decimal(:attack_fire__14,         null: false)
      t.decimal(:attack_fire__15,         null: false)
      t.decimal(:attack_fire__16,         null: false)
      t.decimal(:attack_fire__17,         null: false)
      t.decimal(:attack_fire__18,         null: false)
      t.decimal(:attack_fire__19,         null: false)
      t.decimal(:attack_fire__20,         null: false)
      t.decimal(:attack_fire__21,         null: false)
      t.decimal(:attack_fire__22,         null: false)
      t.decimal(:attack_fire__23,         null: false)
      t.decimal(:attack_fire__24,         null: false)
      t.decimal(:attack_fire__25,         null: false)
      t.decimal(:attack_lightning__0,     null: false)
      t.decimal(:attack_lightning__1,     null: false)
      t.decimal(:attack_lightning__2,     null: false)
      t.decimal(:attack_lightning__3,     null: false)
      t.decimal(:attack_lightning__4,     null: false)
      t.decimal(:attack_lightning__5,     null: false)
      t.decimal(:attack_lightning__6,     null: false)
      t.decimal(:attack_lightning__7,     null: false)
      t.decimal(:attack_lightning__8,     null: false)
      t.decimal(:attack_lightning__9,     null: false)
      t.decimal(:attack_lightning__10,    null: false)
      t.decimal(:attack_lightning__11,    null: false)
      t.decimal(:attack_lightning__12,    null: false)
      t.decimal(:attack_lightning__13,    null: false)
      t.decimal(:attack_lightning__14,    null: false)
      t.decimal(:attack_lightning__15,    null: false)
      t.decimal(:attack_lightning__16,    null: false)
      t.decimal(:attack_lightning__17,    null: false)
      t.decimal(:attack_lightning__18,    null: false)
      t.decimal(:attack_lightning__19,    null: false)
      t.decimal(:attack_lightning__20,    null: false)
      t.decimal(:attack_lightning__21,    null: false)
      t.decimal(:attack_lightning__22,    null: false)
      t.decimal(:attack_lightning__23,    null: false)
      t.decimal(:attack_lightning__24,    null: false)
      t.decimal(:attack_lightning__25,    null: false)
      t.decimal(:attack_holy__0,          null: false)
      t.decimal(:attack_holy__1,          null: false)
      t.decimal(:attack_holy__2,          null: false)
      t.decimal(:attack_holy__3,          null: false)
      t.decimal(:attack_holy__4,          null: false)
      t.decimal(:attack_holy__5,          null: false)
      t.decimal(:attack_holy__6,          null: false)
      t.decimal(:attack_holy__7,          null: false)
      t.decimal(:attack_holy__8,          null: false)
      t.decimal(:attack_holy__9,          null: false)
      t.decimal(:attack_holy__10,         null: false)
      t.decimal(:attack_holy__11,         null: false)
      t.decimal(:attack_holy__12,         null: false)
      t.decimal(:attack_holy__13,         null: false)
      t.decimal(:attack_holy__14,         null: false)
      t.decimal(:attack_holy__15,         null: false)
      t.decimal(:attack_holy__16,         null: false)
      t.decimal(:attack_holy__17,         null: false)
      t.decimal(:attack_holy__18,         null: false)
      t.decimal(:attack_holy__19,         null: false)
      t.decimal(:attack_holy__20,         null: false)
      t.decimal(:attack_holy__21,         null: false)
      t.decimal(:attack_holy__22,         null: false)
      t.decimal(:attack_holy__23,         null: false)
      t.decimal(:attack_holy__24,         null: false)
      t.decimal(:attack_holy__25,         null: false)
      t.decimal(:attack_stamina__0,       null: false)
      t.decimal(:attack_stamina__1,       null: false)
      t.decimal(:attack_stamina__2,       null: false)
      t.decimal(:attack_stamina__3,       null: false)
      t.decimal(:attack_stamina__4,       null: false)
      t.decimal(:attack_stamina__5,       null: false)
      t.decimal(:attack_stamina__6,       null: false)
      t.decimal(:attack_stamina__7,       null: false)
      t.decimal(:attack_stamina__8,       null: false)
      t.decimal(:attack_stamina__9,       null: false)
      t.decimal(:attack_stamina__10,      null: false)
      t.decimal(:attack_stamina__11,      null: false)
      t.decimal(:attack_stamina__12,      null: false)
      t.decimal(:attack_stamina__13,      null: false)
      t.decimal(:attack_stamina__14,      null: false)
      t.decimal(:attack_stamina__15,      null: false)
      t.decimal(:attack_stamina__16,      null: false)
      t.decimal(:attack_stamina__17,      null: false)
      t.decimal(:attack_stamina__18,      null: false)
      t.decimal(:attack_stamina__19,      null: false)
      t.decimal(:attack_stamina__20,      null: false)
      t.decimal(:attack_stamina__21,      null: false)
      t.decimal(:attack_stamina__22,      null: false)
      t.decimal(:attack_stamina__23,      null: false)
      t.decimal(:attack_stamina__24,      null: false)
      t.decimal(:attack_stamina__25,      null: false)

      t.decimal(:scaling_strength__0,      null: false)
      t.decimal(:scaling_strength__1,      null: false)
      t.decimal(:scaling_strength__2,      null: false)
      t.decimal(:scaling_strength__3,      null: false)
      t.decimal(:scaling_strength__4,      null: false)
      t.decimal(:scaling_strength__5,      null: false)
      t.decimal(:scaling_strength__6,      null: false)
      t.decimal(:scaling_strength__7,      null: false)
      t.decimal(:scaling_strength__8,      null: false)
      t.decimal(:scaling_strength__9,      null: false)
      t.decimal(:scaling_strength__10,     null: false)
      t.decimal(:scaling_strength__11,     null: false)
      t.decimal(:scaling_strength__12,     null: false)
      t.decimal(:scaling_strength__13,     null: false)
      t.decimal(:scaling_strength__14,     null: false)
      t.decimal(:scaling_strength__15,     null: false)
      t.decimal(:scaling_strength__16,     null: false)
      t.decimal(:scaling_strength__17,     null: false)
      t.decimal(:scaling_strength__18,     null: false)
      t.decimal(:scaling_strength__19,     null: false)
      t.decimal(:scaling_strength__20,     null: false)
      t.decimal(:scaling_strength__21,     null: false)
      t.decimal(:scaling_strength__22,     null: false)
      t.decimal(:scaling_strength__23,     null: false)
      t.decimal(:scaling_strength__24,     null: false)
      t.decimal(:scaling_strength__25,     null: false)
      t.decimal(:scaling_dexterity__0,     null: false)
      t.decimal(:scaling_dexterity__1,     null: false)
      t.decimal(:scaling_dexterity__2,     null: false)
      t.decimal(:scaling_dexterity__3,     null: false)
      t.decimal(:scaling_dexterity__4,     null: false)
      t.decimal(:scaling_dexterity__5,     null: false)
      t.decimal(:scaling_dexterity__6,     null: false)
      t.decimal(:scaling_dexterity__7,     null: false)
      t.decimal(:scaling_dexterity__8,     null: false)
      t.decimal(:scaling_dexterity__9,     null: false)
      t.decimal(:scaling_dexterity__10,    null: false)
      t.decimal(:scaling_dexterity__11,    null: false)
      t.decimal(:scaling_dexterity__12,    null: false)
      t.decimal(:scaling_dexterity__13,    null: false)
      t.decimal(:scaling_dexterity__14,    null: false)
      t.decimal(:scaling_dexterity__15,    null: false)
      t.decimal(:scaling_dexterity__16,    null: false)
      t.decimal(:scaling_dexterity__17,    null: false)
      t.decimal(:scaling_dexterity__18,    null: false)
      t.decimal(:scaling_dexterity__19,    null: false)
      t.decimal(:scaling_dexterity__20,    null: false)
      t.decimal(:scaling_dexterity__21,    null: false)
      t.decimal(:scaling_dexterity__22,    null: false)
      t.decimal(:scaling_dexterity__23,    null: false)
      t.decimal(:scaling_dexterity__24,    null: false)
      t.decimal(:scaling_dexterity__25,    null: false)
      t.decimal(:scaling_intelligence__0,  null: false)
      t.decimal(:scaling_intelligence__1,  null: false)
      t.decimal(:scaling_intelligence__2,  null: false)
      t.decimal(:scaling_intelligence__3,  null: false)
      t.decimal(:scaling_intelligence__4,  null: false)
      t.decimal(:scaling_intelligence__5,  null: false)
      t.decimal(:scaling_intelligence__6,  null: false)
      t.decimal(:scaling_intelligence__7,  null: false)
      t.decimal(:scaling_intelligence__8,  null: false)
      t.decimal(:scaling_intelligence__9,  null: false)
      t.decimal(:scaling_intelligence__10, null: false)
      t.decimal(:scaling_intelligence__11, null: false)
      t.decimal(:scaling_intelligence__12, null: false)
      t.decimal(:scaling_intelligence__13, null: false)
      t.decimal(:scaling_intelligence__14, null: false)
      t.decimal(:scaling_intelligence__15, null: false)
      t.decimal(:scaling_intelligence__16, null: false)
      t.decimal(:scaling_intelligence__17, null: false)
      t.decimal(:scaling_intelligence__18, null: false)
      t.decimal(:scaling_intelligence__19, null: false)
      t.decimal(:scaling_intelligence__20, null: false)
      t.decimal(:scaling_intelligence__21, null: false)
      t.decimal(:scaling_intelligence__22, null: false)
      t.decimal(:scaling_intelligence__23, null: false)
      t.decimal(:scaling_intelligence__24, null: false)
      t.decimal(:scaling_intelligence__25, null: false)
      t.decimal(:scaling_faith__0,         null: false)
      t.decimal(:scaling_faith__1,         null: false)
      t.decimal(:scaling_faith__2,         null: false)
      t.decimal(:scaling_faith__3,         null: false)
      t.decimal(:scaling_faith__4,         null: false)
      t.decimal(:scaling_faith__5,         null: false)
      t.decimal(:scaling_faith__6,         null: false)
      t.decimal(:scaling_faith__7,         null: false)
      t.decimal(:scaling_faith__8,         null: false)
      t.decimal(:scaling_faith__9,         null: false)
      t.decimal(:scaling_faith__10,        null: false)
      t.decimal(:scaling_faith__11,        null: false)
      t.decimal(:scaling_faith__12,        null: false)
      t.decimal(:scaling_faith__13,        null: false)
      t.decimal(:scaling_faith__14,        null: false)
      t.decimal(:scaling_faith__15,        null: false)
      t.decimal(:scaling_faith__16,        null: false)
      t.decimal(:scaling_faith__17,        null: false)
      t.decimal(:scaling_faith__18,        null: false)
      t.decimal(:scaling_faith__19,        null: false)
      t.decimal(:scaling_faith__20,        null: false)
      t.decimal(:scaling_faith__21,        null: false)
      t.decimal(:scaling_faith__22,        null: false)
      t.decimal(:scaling_faith__23,        null: false)
      t.decimal(:scaling_faith__24,        null: false)
      t.decimal(:scaling_faith__25,        null: false)
      t.decimal(:scaling_arcane__0,        null: false)
      t.decimal(:scaling_arcane__1,        null: false)
      t.decimal(:scaling_arcane__2,        null: false)
      t.decimal(:scaling_arcane__3,        null: false)
      t.decimal(:scaling_arcane__4,        null: false)
      t.decimal(:scaling_arcane__5,        null: false)
      t.decimal(:scaling_arcane__6,        null: false)
      t.decimal(:scaling_arcane__7,        null: false)
      t.decimal(:scaling_arcane__8,        null: false)
      t.decimal(:scaling_arcane__9,        null: false)
      t.decimal(:scaling_arcane__10,       null: false)
      t.decimal(:scaling_arcane__11,       null: false)
      t.decimal(:scaling_arcane__12,       null: false)
      t.decimal(:scaling_arcane__13,       null: false)
      t.decimal(:scaling_arcane__14,       null: false)
      t.decimal(:scaling_arcane__15,       null: false)
      t.decimal(:scaling_arcane__16,       null: false)
      t.decimal(:scaling_arcane__17,       null: false)
      t.decimal(:scaling_arcane__18,       null: false)
      t.decimal(:scaling_arcane__19,       null: false)
      t.decimal(:scaling_arcane__20,       null: false)
      t.decimal(:scaling_arcane__21,       null: false)
      t.decimal(:scaling_arcane__22,       null: false)
      t.decimal(:scaling_arcane__23,       null: false)
      t.decimal(:scaling_arcane__24,       null: false)
      t.decimal(:scaling_arcane__25,       null: false)

      t.timestamps()
    end

    add_foreign_key(
      :weapon_stats,
      :attack_element_correct_params,
      on_delete: :cascade,
    )

    add_foreign_key(
      :weapon_stats,
      :weapons,
      on_delete: :cascade,
    )
    add_foreign_key(
      :weapon_stats,
      :weapon_affinities,
      on_delete: :cascade,
    )

    add_index(
      :weapon_stats,
      [:weapon_id, :weapon_affinity_id],
      name: "index_weapon_stats_on_weapon_and_affinity",
      unique: true,
    )

  end
end
