class CreateWeaponStats < ActiveRecord::Migration[7.0]
  def change()
    create_table(:weapon_stats) do |t|

      t.string(:name, null: false, index: { unique: true })

      t.integer(:attack_element_correct_param_id, null: false, index: true)
      t.integer(:weapon_id,                       null: false, index: true)
      t.integer(:weapon_affinity_id,              null: false, index: true)

      t.decimal(:physical__00,     null: false)
      t.decimal(:physical__01,     null: false)
      t.decimal(:physical__02,     null: false)
      t.decimal(:physical__03,     null: false)
      t.decimal(:physical__04,     null: false)
      t.decimal(:physical__05,     null: false)
      t.decimal(:physical__06,     null: false)
      t.decimal(:physical__07,     null: false)
      t.decimal(:physical__08,     null: false)
      t.decimal(:physical__09,     null: false)
      t.decimal(:physical__10,     null: false)
      t.decimal(:physical__11,     null: false)
      t.decimal(:physical__12,     null: false)
      t.decimal(:physical__13,     null: false)
      t.decimal(:physical__14,     null: false)
      t.decimal(:physical__15,     null: false)
      t.decimal(:physical__16,     null: false)
      t.decimal(:physical__17,     null: false)
      t.decimal(:physical__18,     null: false)
      t.decimal(:physical__19,     null: false)
      t.decimal(:physical__20,     null: false)
      t.decimal(:physical__21,     null: false)
      t.decimal(:physical__22,     null: false)
      t.decimal(:physical__23,     null: false)
      t.decimal(:physical__24,     null: false)
      t.decimal(:physical__25,     null: false)
      t.decimal(:magic__00,        null: false)
      t.decimal(:magic__01,        null: false)
      t.decimal(:magic__02,        null: false)
      t.decimal(:magic__03,        null: false)
      t.decimal(:magic__04,        null: false)
      t.decimal(:magic__05,        null: false)
      t.decimal(:magic__06,        null: false)
      t.decimal(:magic__07,        null: false)
      t.decimal(:magic__08,        null: false)
      t.decimal(:magic__09,        null: false)
      t.decimal(:magic__10,        null: false)
      t.decimal(:magic__11,        null: false)
      t.decimal(:magic__12,        null: false)
      t.decimal(:magic__13,        null: false)
      t.decimal(:magic__14,        null: false)
      t.decimal(:magic__15,        null: false)
      t.decimal(:magic__16,        null: false)
      t.decimal(:magic__17,        null: false)
      t.decimal(:magic__18,        null: false)
      t.decimal(:magic__19,        null: false)
      t.decimal(:magic__20,        null: false)
      t.decimal(:magic__21,        null: false)
      t.decimal(:magic__22,        null: false)
      t.decimal(:magic__23,        null: false)
      t.decimal(:magic__24,        null: false)
      t.decimal(:magic__25,        null: false)
      t.decimal(:fire__00,         null: false)
      t.decimal(:fire__01,         null: false)
      t.decimal(:fire__02,         null: false)
      t.decimal(:fire__03,         null: false)
      t.decimal(:fire__04,         null: false)
      t.decimal(:fire__05,         null: false)
      t.decimal(:fire__06,         null: false)
      t.decimal(:fire__07,         null: false)
      t.decimal(:fire__08,         null: false)
      t.decimal(:fire__09,         null: false)
      t.decimal(:fire__10,         null: false)
      t.decimal(:fire__11,         null: false)
      t.decimal(:fire__12,         null: false)
      t.decimal(:fire__13,         null: false)
      t.decimal(:fire__14,         null: false)
      t.decimal(:fire__15,         null: false)
      t.decimal(:fire__16,         null: false)
      t.decimal(:fire__17,         null: false)
      t.decimal(:fire__18,         null: false)
      t.decimal(:fire__19,         null: false)
      t.decimal(:fire__20,         null: false)
      t.decimal(:fire__21,         null: false)
      t.decimal(:fire__22,         null: false)
      t.decimal(:fire__23,         null: false)
      t.decimal(:fire__24,         null: false)
      t.decimal(:fire__25,         null: false)
      t.decimal(:lightning__00,    null: false)
      t.decimal(:lightning__01,    null: false)
      t.decimal(:lightning__02,    null: false)
      t.decimal(:lightning__03,    null: false)
      t.decimal(:lightning__04,    null: false)
      t.decimal(:lightning__05,    null: false)
      t.decimal(:lightning__06,    null: false)
      t.decimal(:lightning__07,    null: false)
      t.decimal(:lightning__08,    null: false)
      t.decimal(:lightning__09,    null: false)
      t.decimal(:lightning__10,    null: false)
      t.decimal(:lightning__11,    null: false)
      t.decimal(:lightning__12,    null: false)
      t.decimal(:lightning__13,    null: false)
      t.decimal(:lightning__14,    null: false)
      t.decimal(:lightning__15,    null: false)
      t.decimal(:lightning__16,    null: false)
      t.decimal(:lightning__17,    null: false)
      t.decimal(:lightning__18,    null: false)
      t.decimal(:lightning__19,    null: false)
      t.decimal(:lightning__20,    null: false)
      t.decimal(:lightning__21,    null: false)
      t.decimal(:lightning__22,    null: false)
      t.decimal(:lightning__23,    null: false)
      t.decimal(:lightning__24,    null: false)
      t.decimal(:lightning__25,    null: false)
      t.decimal(:holy__00,         null: false)
      t.decimal(:holy__01,         null: false)
      t.decimal(:holy__02,         null: false)
      t.decimal(:holy__03,         null: false)
      t.decimal(:holy__04,         null: false)
      t.decimal(:holy__05,         null: false)
      t.decimal(:holy__06,         null: false)
      t.decimal(:holy__07,         null: false)
      t.decimal(:holy__08,         null: false)
      t.decimal(:holy__09,         null: false)
      t.decimal(:holy__10,         null: false)
      t.decimal(:holy__11,         null: false)
      t.decimal(:holy__12,         null: false)
      t.decimal(:holy__13,         null: false)
      t.decimal(:holy__14,         null: false)
      t.decimal(:holy__15,         null: false)
      t.decimal(:holy__16,         null: false)
      t.decimal(:holy__17,         null: false)
      t.decimal(:holy__18,         null: false)
      t.decimal(:holy__19,         null: false)
      t.decimal(:holy__20,         null: false)
      t.decimal(:holy__21,         null: false)
      t.decimal(:holy__22,         null: false)
      t.decimal(:holy__23,         null: false)
      t.decimal(:holy__24,         null: false)
      t.decimal(:holy__25,         null: false)
      t.decimal(:stamina__00,      null: false)
      t.decimal(:stamina__01,      null: false)
      t.decimal(:stamina__02,      null: false)
      t.decimal(:stamina__03,      null: false)
      t.decimal(:stamina__04,      null: false)
      t.decimal(:stamina__05,      null: false)
      t.decimal(:stamina__06,      null: false)
      t.decimal(:stamina__07,      null: false)
      t.decimal(:stamina__08,      null: false)
      t.decimal(:stamina__09,      null: false)
      t.decimal(:stamina__10,      null: false)
      t.decimal(:stamina__11,      null: false)
      t.decimal(:stamina__12,      null: false)
      t.decimal(:stamina__13,      null: false)
      t.decimal(:stamina__14,      null: false)
      t.decimal(:stamina__15,      null: false)
      t.decimal(:stamina__16,      null: false)
      t.decimal(:stamina__17,      null: false)
      t.decimal(:stamina__18,      null: false)
      t.decimal(:stamina__19,      null: false)
      t.decimal(:stamina__20,      null: false)
      t.decimal(:stamina__21,      null: false)
      t.decimal(:stamina__22,      null: false)
      t.decimal(:stamina__23,      null: false)
      t.decimal(:stamina__24,      null: false)
      t.decimal(:stamina__25,      null: false)

      t.decimal(:strength__00,     null: false)
      t.decimal(:strength__01,     null: false)
      t.decimal(:strength__02,     null: false)
      t.decimal(:strength__03,     null: false)
      t.decimal(:strength__04,     null: false)
      t.decimal(:strength__05,     null: false)
      t.decimal(:strength__06,     null: false)
      t.decimal(:strength__07,     null: false)
      t.decimal(:strength__08,     null: false)
      t.decimal(:strength__09,     null: false)
      t.decimal(:strength__10,     null: false)
      t.decimal(:strength__11,     null: false)
      t.decimal(:strength__12,     null: false)
      t.decimal(:strength__13,     null: false)
      t.decimal(:strength__14,     null: false)
      t.decimal(:strength__15,     null: false)
      t.decimal(:strength__16,     null: false)
      t.decimal(:strength__17,     null: false)
      t.decimal(:strength__18,     null: false)
      t.decimal(:strength__19,     null: false)
      t.decimal(:strength__20,     null: false)
      t.decimal(:strength__21,     null: false)
      t.decimal(:strength__22,     null: false)
      t.decimal(:strength__23,     null: false)
      t.decimal(:strength__24,     null: false)
      t.decimal(:strength__25,     null: false)
      t.decimal(:dexterity__00,    null: false)
      t.decimal(:dexterity__01,    null: false)
      t.decimal(:dexterity__02,    null: false)
      t.decimal(:dexterity__03,    null: false)
      t.decimal(:dexterity__04,    null: false)
      t.decimal(:dexterity__05,    null: false)
      t.decimal(:dexterity__06,    null: false)
      t.decimal(:dexterity__07,    null: false)
      t.decimal(:dexterity__08,    null: false)
      t.decimal(:dexterity__09,    null: false)
      t.decimal(:dexterity__10,    null: false)
      t.decimal(:dexterity__11,    null: false)
      t.decimal(:dexterity__12,    null: false)
      t.decimal(:dexterity__13,    null: false)
      t.decimal(:dexterity__14,    null: false)
      t.decimal(:dexterity__15,    null: false)
      t.decimal(:dexterity__16,    null: false)
      t.decimal(:dexterity__17,    null: false)
      t.decimal(:dexterity__18,    null: false)
      t.decimal(:dexterity__19,    null: false)
      t.decimal(:dexterity__20,    null: false)
      t.decimal(:dexterity__21,    null: false)
      t.decimal(:dexterity__22,    null: false)
      t.decimal(:dexterity__23,    null: false)
      t.decimal(:dexterity__24,    null: false)
      t.decimal(:dexterity__25,    null: false)
      t.decimal(:intelligence__00, null: false)
      t.decimal(:intelligence__01, null: false)
      t.decimal(:intelligence__02, null: false)
      t.decimal(:intelligence__03, null: false)
      t.decimal(:intelligence__04, null: false)
      t.decimal(:intelligence__05, null: false)
      t.decimal(:intelligence__06, null: false)
      t.decimal(:intelligence__07, null: false)
      t.decimal(:intelligence__08, null: false)
      t.decimal(:intelligence__09, null: false)
      t.decimal(:intelligence__10, null: false)
      t.decimal(:intelligence__11, null: false)
      t.decimal(:intelligence__12, null: false)
      t.decimal(:intelligence__13, null: false)
      t.decimal(:intelligence__14, null: false)
      t.decimal(:intelligence__15, null: false)
      t.decimal(:intelligence__16, null: false)
      t.decimal(:intelligence__17, null: false)
      t.decimal(:intelligence__18, null: false)
      t.decimal(:intelligence__19, null: false)
      t.decimal(:intelligence__20, null: false)
      t.decimal(:intelligence__21, null: false)
      t.decimal(:intelligence__22, null: false)
      t.decimal(:intelligence__23, null: false)
      t.decimal(:intelligence__24, null: false)
      t.decimal(:intelligence__25, null: false)
      t.decimal(:faith__00,        null: false)
      t.decimal(:faith__01,        null: false)
      t.decimal(:faith__02,        null: false)
      t.decimal(:faith__03,        null: false)
      t.decimal(:faith__04,        null: false)
      t.decimal(:faith__05,        null: false)
      t.decimal(:faith__06,        null: false)
      t.decimal(:faith__07,        null: false)
      t.decimal(:faith__08,        null: false)
      t.decimal(:faith__09,        null: false)
      t.decimal(:faith__10,        null: false)
      t.decimal(:faith__11,        null: false)
      t.decimal(:faith__12,        null: false)
      t.decimal(:faith__13,        null: false)
      t.decimal(:faith__14,        null: false)
      t.decimal(:faith__15,        null: false)
      t.decimal(:faith__16,        null: false)
      t.decimal(:faith__17,        null: false)
      t.decimal(:faith__18,        null: false)
      t.decimal(:faith__19,        null: false)
      t.decimal(:faith__20,        null: false)
      t.decimal(:faith__21,        null: false)
      t.decimal(:faith__22,        null: false)
      t.decimal(:faith__23,        null: false)
      t.decimal(:faith__24,        null: false)
      t.decimal(:faith__25,        null: false)
      t.decimal(:arcane__00,       null: false)
      t.decimal(:arcane__01,       null: false)
      t.decimal(:arcane__02,       null: false)
      t.decimal(:arcane__03,       null: false)
      t.decimal(:arcane__04,       null: false)
      t.decimal(:arcane__05,       null: false)
      t.decimal(:arcane__06,       null: false)
      t.decimal(:arcane__07,       null: false)
      t.decimal(:arcane__08,       null: false)
      t.decimal(:arcane__09,       null: false)
      t.decimal(:arcane__10,       null: false)
      t.decimal(:arcane__11,       null: false)
      t.decimal(:arcane__12,       null: false)
      t.decimal(:arcane__13,       null: false)
      t.decimal(:arcane__14,       null: false)
      t.decimal(:arcane__15,       null: false)
      t.decimal(:arcane__16,       null: false)
      t.decimal(:arcane__17,       null: false)
      t.decimal(:arcane__18,       null: false)
      t.decimal(:arcane__19,       null: false)
      t.decimal(:arcane__20,       null: false)
      t.decimal(:arcane__21,       null: false)
      t.decimal(:arcane__22,       null: false)
      t.decimal(:arcane__23,       null: false)
      t.decimal(:arcane__24,       null: false)
      t.decimal(:arcane__25,       null: false)

      t.timestamps()
    end

    add_foreign_key(
      :weapon_stats,
      :attack_element_correct_params,
      on_delete: :cascade,
    )

    add_foreign_key(
      :weapon_stats,
      :weapons,
      on_delete: :cascade,
    )
    add_foreign_key(
      :weapon_stats,
      :weapon_affinities,
      on_delete: :cascade,
    )

    add_index(
      :weapon_stats,
      [:weapon_id, :weapon_affinity_id],
      name: "index_weapon_stats_on_weapon_and_affinity",
      unique: true,
    )

  end
end
