class CreateWeaponStats < ActiveRecord::Migration[7.0]
  def change()
    create_table(:weapon_stats) do |t|

      t.string(:name, null: false, index: { unique: true })

      t.integer(:attack_element_correct_param_id, null: false, index: true)
      t.integer(:weapon_id,                       null: false, index: true)
      t.integer(:weapon_affinity_id,              null: false, index: true)

      t.decimal(:attack_physical_0,      null: false)
      t.decimal(:attack_physical_1,      null: false)
      t.decimal(:attack_physical_2,      null: false)
      t.decimal(:attack_physical_3,      null: false)
      t.decimal(:attack_physical_4,      null: false)
      t.decimal(:attack_physical_5,      null: false)
      t.decimal(:attack_physical_6,      null: false)
      t.decimal(:attack_physical_7,      null: false)
      t.decimal(:attack_physical_8,      null: false)
      t.decimal(:attack_physical_9,      null: false)
      t.decimal(:attack_physical_10,     null: false)
      t.decimal(:attack_physical_11,     null: false)
      t.decimal(:attack_physical_12,     null: false)
      t.decimal(:attack_physical_13,     null: false)
      t.decimal(:attack_physical_14,     null: false)
      t.decimal(:attack_physical_15,     null: false)
      t.decimal(:attack_physical_16,     null: false)
      t.decimal(:attack_physical_17,     null: false)
      t.decimal(:attack_physical_18,     null: false)
      t.decimal(:attack_physical_19,     null: false)
      t.decimal(:attack_physical_20,     null: false)
      t.decimal(:attack_physical_21,     null: false)
      t.decimal(:attack_physical_22,     null: false)
      t.decimal(:attack_physical_23,     null: false)
      t.decimal(:attack_physical_24,     null: false)
      t.decimal(:attack_physical_25,     null: false)
      t.decimal(:attack_magic_0,         null: false)
      t.decimal(:attack_magic_1,         null: false)
      t.decimal(:attack_magic_2,         null: false)
      t.decimal(:attack_magic_3,         null: false)
      t.decimal(:attack_magic_4,         null: false)
      t.decimal(:attack_magic_5,         null: false)
      t.decimal(:attack_magic_6,         null: false)
      t.decimal(:attack_magic_7,         null: false)
      t.decimal(:attack_magic_8,         null: false)
      t.decimal(:attack_magic_9,         null: false)
      t.decimal(:attack_magic_10,        null: false)
      t.decimal(:attack_magic_11,        null: false)
      t.decimal(:attack_magic_12,        null: false)
      t.decimal(:attack_magic_13,        null: false)
      t.decimal(:attack_magic_14,        null: false)
      t.decimal(:attack_magic_15,        null: false)
      t.decimal(:attack_magic_16,        null: false)
      t.decimal(:attack_magic_17,        null: false)
      t.decimal(:attack_magic_18,        null: false)
      t.decimal(:attack_magic_19,        null: false)
      t.decimal(:attack_magic_20,        null: false)
      t.decimal(:attack_magic_21,        null: false)
      t.decimal(:attack_magic_22,        null: false)
      t.decimal(:attack_magic_23,        null: false)
      t.decimal(:attack_magic_24,        null: false)
      t.decimal(:attack_magic_25,        null: false)
      t.decimal(:attack_fire_0,          null: false)
      t.decimal(:attack_fire_1,          null: false)
      t.decimal(:attack_fire_2,          null: false)
      t.decimal(:attack_fire_3,          null: false)
      t.decimal(:attack_fire_4,          null: false)
      t.decimal(:attack_fire_5,          null: false)
      t.decimal(:attack_fire_6,          null: false)
      t.decimal(:attack_fire_7,          null: false)
      t.decimal(:attack_fire_8,          null: false)
      t.decimal(:attack_fire_9,          null: false)
      t.decimal(:attack_fire_10,         null: false)
      t.decimal(:attack_fire_11,         null: false)
      t.decimal(:attack_fire_12,         null: false)
      t.decimal(:attack_fire_13,         null: false)
      t.decimal(:attack_fire_14,         null: false)
      t.decimal(:attack_fire_15,         null: false)
      t.decimal(:attack_fire_16,         null: false)
      t.decimal(:attack_fire_17,         null: false)
      t.decimal(:attack_fire_18,         null: false)
      t.decimal(:attack_fire_19,         null: false)
      t.decimal(:attack_fire_20,         null: false)
      t.decimal(:attack_fire_21,         null: false)
      t.decimal(:attack_fire_22,         null: false)
      t.decimal(:attack_fire_23,         null: false)
      t.decimal(:attack_fire_24,         null: false)
      t.decimal(:attack_fire_25,         null: false)
      t.decimal(:attack_lightning_0,     null: false)
      t.decimal(:attack_lightning_1,     null: false)
      t.decimal(:attack_lightning_2,     null: false)
      t.decimal(:attack_lightning_3,     null: false)
      t.decimal(:attack_lightning_4,     null: false)
      t.decimal(:attack_lightning_5,     null: false)
      t.decimal(:attack_lightning_6,     null: false)
      t.decimal(:attack_lightning_7,     null: false)
      t.decimal(:attack_lightning_8,     null: false)
      t.decimal(:attack_lightning_9,     null: false)
      t.decimal(:attack_lightning_10,    null: false)
      t.decimal(:attack_lightning_11,    null: false)
      t.decimal(:attack_lightning_12,    null: false)
      t.decimal(:attack_lightning_13,    null: false)
      t.decimal(:attack_lightning_14,    null: false)
      t.decimal(:attack_lightning_15,    null: false)
      t.decimal(:attack_lightning_16,    null: false)
      t.decimal(:attack_lightning_17,    null: false)
      t.decimal(:attack_lightning_18,    null: false)
      t.decimal(:attack_lightning_19,    null: false)
      t.decimal(:attack_lightning_20,    null: false)
      t.decimal(:attack_lightning_21,    null: false)
      t.decimal(:attack_lightning_22,    null: false)
      t.decimal(:attack_lightning_23,    null: false)
      t.decimal(:attack_lightning_24,    null: false)
      t.decimal(:attack_lightning_25,    null: false)
      t.decimal(:attack_holy_0,          null: false)
      t.decimal(:attack_holy_1,          null: false)
      t.decimal(:attack_holy_2,          null: false)
      t.decimal(:attack_holy_3,          null: false)
      t.decimal(:attack_holy_4,          null: false)
      t.decimal(:attack_holy_5,          null: false)
      t.decimal(:attack_holy_6,          null: false)
      t.decimal(:attack_holy_7,          null: false)
      t.decimal(:attack_holy_8,          null: false)
      t.decimal(:attack_holy_9,          null: false)
      t.decimal(:attack_holy_10,         null: false)
      t.decimal(:attack_holy_11,         null: false)
      t.decimal(:attack_holy_12,         null: false)
      t.decimal(:attack_holy_13,         null: false)
      t.decimal(:attack_holy_14,         null: false)
      t.decimal(:attack_holy_15,         null: false)
      t.decimal(:attack_holy_16,         null: false)
      t.decimal(:attack_holy_17,         null: false)
      t.decimal(:attack_holy_18,         null: false)
      t.decimal(:attack_holy_19,         null: false)
      t.decimal(:attack_holy_20,         null: false)
      t.decimal(:attack_holy_21,         null: false)
      t.decimal(:attack_holy_22,         null: false)
      t.decimal(:attack_holy_23,         null: false)
      t.decimal(:attack_holy_24,         null: false)
      t.decimal(:attack_holy_25,         null: false)
      t.decimal(:attack_stamina_0,       null: false)
      t.decimal(:attack_stamina_1,       null: false)
      t.decimal(:attack_stamina_2,       null: false)
      t.decimal(:attack_stamina_3,       null: false)
      t.decimal(:attack_stamina_4,       null: false)
      t.decimal(:attack_stamina_5,       null: false)
      t.decimal(:attack_stamina_6,       null: false)
      t.decimal(:attack_stamina_7,       null: false)
      t.decimal(:attack_stamina_8,       null: false)
      t.decimal(:attack_stamina_9,       null: false)
      t.decimal(:attack_stamina_10,      null: false)
      t.decimal(:attack_stamina_11,      null: false)
      t.decimal(:attack_stamina_12,      null: false)
      t.decimal(:attack_stamina_13,      null: false)
      t.decimal(:attack_stamina_14,      null: false)
      t.decimal(:attack_stamina_15,      null: false)
      t.decimal(:attack_stamina_16,      null: false)
      t.decimal(:attack_stamina_17,      null: false)
      t.decimal(:attack_stamina_18,      null: false)
      t.decimal(:attack_stamina_19,      null: false)
      t.decimal(:attack_stamina_20,      null: false)
      t.decimal(:attack_stamina_21,      null: false)
      t.decimal(:attack_stamina_22,      null: false)
      t.decimal(:attack_stamina_23,      null: false)
      t.decimal(:attack_stamina_24,      null: false)
      t.decimal(:attack_stamina_25,      null: false)

      t.decimal(:scaling_strength_0,      null: false)
      t.decimal(:scaling_strength_1,      null: false)
      t.decimal(:scaling_strength_2,      null: false)
      t.decimal(:scaling_strength_3,      null: false)
      t.decimal(:scaling_strength_4,      null: false)
      t.decimal(:scaling_strength_5,      null: false)
      t.decimal(:scaling_strength_6,      null: false)
      t.decimal(:scaling_strength_7,      null: false)
      t.decimal(:scaling_strength_8,      null: false)
      t.decimal(:scaling_strength_9,      null: false)
      t.decimal(:scaling_strength_10,     null: false)
      t.decimal(:scaling_strength_11,     null: false)
      t.decimal(:scaling_strength_12,     null: false)
      t.decimal(:scaling_strength_13,     null: false)
      t.decimal(:scaling_strength_14,     null: false)
      t.decimal(:scaling_strength_15,     null: false)
      t.decimal(:scaling_strength_16,     null: false)
      t.decimal(:scaling_strength_17,     null: false)
      t.decimal(:scaling_strength_18,     null: false)
      t.decimal(:scaling_strength_19,     null: false)
      t.decimal(:scaling_strength_20,     null: false)
      t.decimal(:scaling_strength_21,     null: false)
      t.decimal(:scaling_strength_22,     null: false)
      t.decimal(:scaling_strength_23,     null: false)
      t.decimal(:scaling_strength_24,     null: false)
      t.decimal(:scaling_strength_25,     null: false)
      t.decimal(:scaling_dexterity_0,     null: false)
      t.decimal(:scaling_dexterity_1,     null: false)
      t.decimal(:scaling_dexterity_2,     null: false)
      t.decimal(:scaling_dexterity_3,     null: false)
      t.decimal(:scaling_dexterity_4,     null: false)
      t.decimal(:scaling_dexterity_5,     null: false)
      t.decimal(:scaling_dexterity_6,     null: false)
      t.decimal(:scaling_dexterity_7,     null: false)
      t.decimal(:scaling_dexterity_8,     null: false)
      t.decimal(:scaling_dexterity_9,     null: false)
      t.decimal(:scaling_dexterity_10,    null: false)
      t.decimal(:scaling_dexterity_11,    null: false)
      t.decimal(:scaling_dexterity_12,    null: false)
      t.decimal(:scaling_dexterity_13,    null: false)
      t.decimal(:scaling_dexterity_14,    null: false)
      t.decimal(:scaling_dexterity_15,    null: false)
      t.decimal(:scaling_dexterity_16,    null: false)
      t.decimal(:scaling_dexterity_17,    null: false)
      t.decimal(:scaling_dexterity_18,    null: false)
      t.decimal(:scaling_dexterity_19,    null: false)
      t.decimal(:scaling_dexterity_20,    null: false)
      t.decimal(:scaling_dexterity_21,    null: false)
      t.decimal(:scaling_dexterity_22,    null: false)
      t.decimal(:scaling_dexterity_23,    null: false)
      t.decimal(:scaling_dexterity_24,    null: false)
      t.decimal(:scaling_dexterity_25,    null: false)
      t.decimal(:scaling_intelligence_0,  null: false)
      t.decimal(:scaling_intelligence_1,  null: false)
      t.decimal(:scaling_intelligence_2,  null: false)
      t.decimal(:scaling_intelligence_3,  null: false)
      t.decimal(:scaling_intelligence_4,  null: false)
      t.decimal(:scaling_intelligence_5,  null: false)
      t.decimal(:scaling_intelligence_6,  null: false)
      t.decimal(:scaling_intelligence_7,  null: false)
      t.decimal(:scaling_intelligence_8,  null: false)
      t.decimal(:scaling_intelligence_9,  null: false)
      t.decimal(:scaling_intelligence_10, null: false)
      t.decimal(:scaling_intelligence_11, null: false)
      t.decimal(:scaling_intelligence_12, null: false)
      t.decimal(:scaling_intelligence_13, null: false)
      t.decimal(:scaling_intelligence_14, null: false)
      t.decimal(:scaling_intelligence_15, null: false)
      t.decimal(:scaling_intelligence_16, null: false)
      t.decimal(:scaling_intelligence_17, null: false)
      t.decimal(:scaling_intelligence_18, null: false)
      t.decimal(:scaling_intelligence_19, null: false)
      t.decimal(:scaling_intelligence_20, null: false)
      t.decimal(:scaling_intelligence_21, null: false)
      t.decimal(:scaling_intelligence_22, null: false)
      t.decimal(:scaling_intelligence_23, null: false)
      t.decimal(:scaling_intelligence_24, null: false)
      t.decimal(:scaling_intelligence_25, null: false)
      t.decimal(:scaling_faith_0,         null: false)
      t.decimal(:scaling_faith_1,         null: false)
      t.decimal(:scaling_faith_2,         null: false)
      t.decimal(:scaling_faith_3,         null: false)
      t.decimal(:scaling_faith_4,         null: false)
      t.decimal(:scaling_faith_5,         null: false)
      t.decimal(:scaling_faith_6,         null: false)
      t.decimal(:scaling_faith_7,         null: false)
      t.decimal(:scaling_faith_8,         null: false)
      t.decimal(:scaling_faith_9,         null: false)
      t.decimal(:scaling_faith_10,        null: false)
      t.decimal(:scaling_faith_11,        null: false)
      t.decimal(:scaling_faith_12,        null: false)
      t.decimal(:scaling_faith_13,        null: false)
      t.decimal(:scaling_faith_14,        null: false)
      t.decimal(:scaling_faith_15,        null: false)
      t.decimal(:scaling_faith_16,        null: false)
      t.decimal(:scaling_faith_17,        null: false)
      t.decimal(:scaling_faith_18,        null: false)
      t.decimal(:scaling_faith_19,        null: false)
      t.decimal(:scaling_faith_20,        null: false)
      t.decimal(:scaling_faith_21,        null: false)
      t.decimal(:scaling_faith_22,        null: false)
      t.decimal(:scaling_faith_23,        null: false)
      t.decimal(:scaling_faith_24,        null: false)
      t.decimal(:scaling_faith_25,        null: false)
      t.decimal(:scaling_arcane_0,        null: false)
      t.decimal(:scaling_arcane_1,        null: false)
      t.decimal(:scaling_arcane_2,        null: false)
      t.decimal(:scaling_arcane_3,        null: false)
      t.decimal(:scaling_arcane_4,        null: false)
      t.decimal(:scaling_arcane_5,        null: false)
      t.decimal(:scaling_arcane_6,        null: false)
      t.decimal(:scaling_arcane_7,        null: false)
      t.decimal(:scaling_arcane_8,        null: false)
      t.decimal(:scaling_arcane_9,        null: false)
      t.decimal(:scaling_arcane_10,       null: false)
      t.decimal(:scaling_arcane_11,       null: false)
      t.decimal(:scaling_arcane_12,       null: false)
      t.decimal(:scaling_arcane_13,       null: false)
      t.decimal(:scaling_arcane_14,       null: false)
      t.decimal(:scaling_arcane_15,       null: false)
      t.decimal(:scaling_arcane_16,       null: false)
      t.decimal(:scaling_arcane_17,       null: false)
      t.decimal(:scaling_arcane_18,       null: false)
      t.decimal(:scaling_arcane_19,       null: false)
      t.decimal(:scaling_arcane_20,       null: false)
      t.decimal(:scaling_arcane_21,       null: false)
      t.decimal(:scaling_arcane_22,       null: false)
      t.decimal(:scaling_arcane_23,       null: false)
      t.decimal(:scaling_arcane_24,       null: false)
      t.decimal(:scaling_arcane_25,       null: false)

      t.timestamps()
    end

    add_foreign_key(
      :weapon_stats,
      :attack_element_correct_params,
      on_delete: :cascade,
    )

    add_foreign_key(
      :weapon_stats,
      :weapons,
      on_delete: :cascade,
    )
    add_foreign_key(
      :weapon_stats,
      :weapon_affinities,
      on_delete: :cascade,
    )

    add_index(
      :weapon_stats,
      [:weapon_id, :weapon_affinity_id],
      name: "index_weapon_stats_on_weapon_and_affinity",
      unique: true,
    )

  end
end
