class AddPassiveDamageToWeaponStat < ActiveRecord::Migration[7.0]
  def change()
    change_table(:weapon_stats) do |t|

      t.string(:passive_type_1)
      t.string(:passive_type_2)

      t.integer(:passive_scarlet_rot_0, null: false, default: 0)
      t.integer(:passive_madness_0,     null: false, default: 0)
      t.integer(:passive_sleep_0,       null: false, default: 0)
      t.integer(:passive_frost_0,       null: false, default: 0)
      t.integer(:passive_poison_0,      null: false, default: 0)
      t.integer(:passive_blood_loss_0,  null: false, default: 0)
      t.integer(:passive_frost_1,       null: false, default: 0)
      t.integer(:passive_poison_1,      null: false, default: 0)
      t.integer(:passive_blood_loss_1,  null: false, default: 0)
      t.integer(:passive_frost_2,       null: false, default: 0)
      t.integer(:passive_poison_2,      null: false, default: 0)
      t.integer(:passive_blood_loss_2,  null: false, default: 0)
      t.integer(:passive_frost_3,       null: false, default: 0)
      t.integer(:passive_poison_3,      null: false, default: 0)
      t.integer(:passive_blood_loss_3,  null: false, default: 0)
      t.integer(:passive_frost_4,       null: false, default: 0)
      t.integer(:passive_poison_4,      null: false, default: 0)
      t.integer(:passive_blood_loss_4,  null: false, default: 0)
      t.integer(:passive_frost_5,       null: false, default: 0)
      t.integer(:passive_poison_5,      null: false, default: 0)
      t.integer(:passive_blood_loss_5,  null: false, default: 0)
      t.integer(:passive_frost_6,       null: false, default: 0)
      t.integer(:passive_poison_6,      null: false, default: 0)
      t.integer(:passive_blood_loss_6,  null: false, default: 0)
      t.integer(:passive_frost_7,       null: false, default: 0)
      t.integer(:passive_poison_7,      null: false, default: 0)
      t.integer(:passive_blood_loss_7,  null: false, default: 0)
      t.integer(:passive_frost_8,       null: false, default: 0)
      t.integer(:passive_poison_8,      null: false, default: 0)
      t.integer(:passive_blood_loss_8,  null: false, default: 0)
      t.integer(:passive_frost_9,       null: false, default: 0)
      t.integer(:passive_poison_9,      null: false, default: 0)
      t.integer(:passive_blood_loss_9,  null: false, default: 0)
      t.integer(:passive_frost_10,      null: false, default: 0)
      t.integer(:passive_poison_10,     null: false, default: 0)
      t.integer(:passive_blood_loss_10, null: false, default: 0)
      t.integer(:passive_frost_11,      null: false, default: 0)
      t.integer(:passive_poison_11,     null: false, default: 0)
      t.integer(:passive_blood_loss_11, null: false, default: 0)
      t.integer(:passive_frost_12,      null: false, default: 0)
      t.integer(:passive_poison_12,     null: false, default: 0)
      t.integer(:passive_blood_loss_12, null: false, default: 0)
      t.integer(:passive_frost_13,      null: false, default: 0)
      t.integer(:passive_poison_13,     null: false, default: 0)
      t.integer(:passive_blood_loss_13, null: false, default: 0)
      t.integer(:passive_frost_14,      null: false, default: 0)
      t.integer(:passive_poison_14,     null: false, default: 0)
      t.integer(:passive_blood_loss_14, null: false, default: 0)
      t.integer(:passive_frost_15,      null: false, default: 0)
      t.integer(:passive_poison_15,     null: false, default: 0)
      t.integer(:passive_blood_loss_15, null: false, default: 0)
      t.integer(:passive_frost_16,      null: false, default: 0)
      t.integer(:passive_poison_16,     null: false, default: 0)
      t.integer(:passive_blood_loss_16, null: false, default: 0)
      t.integer(:passive_frost_17,      null: false, default: 0)
      t.integer(:passive_poison_17,     null: false, default: 0)
      t.integer(:passive_blood_loss_17, null: false, default: 0)
      t.integer(:passive_frost_18,      null: false, default: 0)
      t.integer(:passive_poison_18,     null: false, default: 0)
      t.integer(:passive_blood_loss_18, null: false, default: 0)
      t.integer(:passive_frost_19,      null: false, default: 0)
      t.integer(:passive_poison_19,     null: false, default: 0)
      t.integer(:passive_blood_loss_19, null: false, default: 0)
      t.integer(:passive_frost_20,      null: false, default: 0)
      t.integer(:passive_poison_20,     null: false, default: 0)
      t.integer(:passive_blood_loss_20, null: false, default: 0)
      t.integer(:passive_frost_21,      null: false, default: 0)
      t.integer(:passive_poison_21,     null: false, default: 0)
      t.integer(:passive_blood_loss_21, null: false, default: 0)
      t.integer(:passive_frost_22,      null: false, default: 0)
      t.integer(:passive_poison_22,     null: false, default: 0)
      t.integer(:passive_blood_loss_22, null: false, default: 0)
      t.integer(:passive_frost_23,      null: false, default: 0)
      t.integer(:passive_poison_23,     null: false, default: 0)
      t.integer(:passive_blood_loss_23, null: false, default: 0)
      t.integer(:passive_frost_24,      null: false, default: 0)
      t.integer(:passive_poison_24,     null: false, default: 0)
      t.integer(:passive_blood_loss_24, null: false, default: 0)
      t.integer(:passive_frost_25,      null: false, default: 0)
      t.integer(:passive_poison_25,     null: false, default: 0)
      t.integer(:passive_blood_loss_25, null: false, default: 0)

    end
  end
end
