default: &default
  adapter: postgresql
  encoding: unicode
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= Rails.application.credentials.dig(Rails.env.to_sym, :db, :database) %>
  username: <%= Rails.application.credentials.dig(Rails.env.to_sym, :db, :username) %>
  password: <%= Rails.application.credentials.dig(Rails.env.to_sym, :db, :password) %>
  host:     <%= Rails.application.credentials.dig(Rails.env.to_sym, :db, :host) %>

development:
  <<: *default

test:
  <<: *default
  database: elden_ring_test # fixes rails/rake db tasks

production:
  <<: *default
