class WeaponStat < ApplicationRecord
  # ============================================================================
  # Attributes
  # ============================================================================

  # @!group Attributes

  # @!attribute name
  #   @return [String]
  validates(:name, presence: true, uniqueness: true)

  # @!attribute attack_physical__0
  #   @return [Decimal]
  # @!attribute attack_physical__1
  #   @return [Decimal]
  # @!attribute attack_physical__2
  #   @return [Decimal]
  # @!attribute attack_physical__3
  #   @return [Decimal]
  # @!attribute attack_physical__4
  #   @return [Decimal]
  # @!attribute attack_physical__5
  #   @return [Decimal]
  # @!attribute attack_physical__6
  #   @return [Decimal]
  # @!attribute attack_physical__7
  #   @return [Decimal]
  # @!attribute attack_physical__8
  #   @return [Decimal]
  # @!attribute attack_physical__9
  #   @return [Decimal]
  # @!attribute attack_physical__10
  #   @return [Decimal]
  # @!attribute attack_physical__11
  #   @return [Decimal]
  # @!attribute attack_physical__12
  #   @return [Decimal]
  # @!attribute attack_physical__13
  #   @return [Decimal]
  # @!attribute attack_physical__14
  #   @return [Decimal]
  # @!attribute attack_physical__15
  #   @return [Decimal]
  # @!attribute attack_physical__16
  #   @return [Decimal]
  # @!attribute attack_physical__17
  #   @return [Decimal]
  # @!attribute attack_physical__18
  #   @return [Decimal]
  # @!attribute attack_physical__19
  #   @return [Decimal]
  # @!attribute attack_physical__20
  #   @return [Decimal]
  # @!attribute attack_physical__21
  #   @return [Decimal]
  # @!attribute attack_physical__22
  #   @return [Decimal]
  # @!attribute attack_physical__23
  #   @return [Decimal]
  # @!attribute attack_physical__24
  #   @return [Decimal]
  # @!attribute attack_physical__25
  #   @return [Decimal]
  # @!attribute attack_magic__0
  #   @return [Decimal]
  # @!attribute attack_magic__1
  #   @return [Decimal]
  # @!attribute attack_magic__2
  #   @return [Decimal]
  # @!attribute attack_magic__3
  #   @return [Decimal]
  # @!attribute attack_magic__4
  #   @return [Decimal]
  # @!attribute attack_magic__5
  #   @return [Decimal]
  # @!attribute attack_magic__6
  #   @return [Decimal]
  # @!attribute attack_magic__7
  #   @return [Decimal]
  # @!attribute attack_magic__8
  #   @return [Decimal]
  # @!attribute attack_magic__9
  #   @return [Decimal]
  # @!attribute attack_magic__10
  #   @return [Decimal]
  # @!attribute attack_magic__11
  #   @return [Decimal]
  # @!attribute attack_magic__12
  #   @return [Decimal]
  # @!attribute attack_magic__13
  #   @return [Decimal]
  # @!attribute attack_magic__14
  #   @return [Decimal]
  # @!attribute attack_magic__15
  #   @return [Decimal]
  # @!attribute attack_magic__16
  #   @return [Decimal]
  # @!attribute attack_magic__17
  #   @return [Decimal]
  # @!attribute attack_magic__18
  #   @return [Decimal]
  # @!attribute attack_magic__19
  #   @return [Decimal]
  # @!attribute attack_magic__20
  #   @return [Decimal]
  # @!attribute attack_magic__21
  #   @return [Decimal]
  # @!attribute attack_magic__22
  #   @return [Decimal]
  # @!attribute attack_magic__23
  #   @return [Decimal]
  # @!attribute attack_magic__24
  #   @return [Decimal]
  # @!attribute attack_magic__25
  #   @return [Decimal]
  # @!attribute attack_fire__0
  #   @return [Decimal]
  # @!attribute attack_fire__1
  #   @return [Decimal]
  # @!attribute attack_fire__2
  #   @return [Decimal]
  # @!attribute attack_fire__3
  #   @return [Decimal]
  # @!attribute attack_fire__4
  #   @return [Decimal]
  # @!attribute attack_fire__5
  #   @return [Decimal]
  # @!attribute attack_fire__6
  #   @return [Decimal]
  # @!attribute attack_fire__7
  #   @return [Decimal]
  # @!attribute attack_fire__8
  #   @return [Decimal]
  # @!attribute attack_fire__9
  #   @return [Decimal]
  # @!attribute attack_fire__10
  #   @return [Decimal]
  # @!attribute attack_fire__11
  #   @return [Decimal]
  # @!attribute attack_fire__12
  #   @return [Decimal]
  # @!attribute attack_fire__13
  #   @return [Decimal]
  # @!attribute attack_fire__14
  #   @return [Decimal]
  # @!attribute attack_fire__15
  #   @return [Decimal]
  # @!attribute attack_fire__16
  #   @return [Decimal]
  # @!attribute attack_fire__17
  #   @return [Decimal]
  # @!attribute attack_fire__18
  #   @return [Decimal]
  # @!attribute attack_fire__19
  #   @return [Decimal]
  # @!attribute attack_fire__20
  #   @return [Decimal]
  # @!attribute attack_fire__21
  #   @return [Decimal]
  # @!attribute attack_fire__22
  #   @return [Decimal]
  # @!attribute attack_fire__23
  #   @return [Decimal]
  # @!attribute attack_fire__24
  #   @return [Decimal]
  # @!attribute attack_fire__25
  #   @return [Decimal]
  # @!attribute attack_lightning__0
  #   @return [Decimal]
  # @!attribute attack_lightning__1
  #   @return [Decimal]
  # @!attribute attack_lightning__2
  #   @return [Decimal]
  # @!attribute attack_lightning__3
  #   @return [Decimal]
  # @!attribute attack_lightning__4
  #   @return [Decimal]
  # @!attribute attack_lightning__5
  #   @return [Decimal]
  # @!attribute attack_lightning__6
  #   @return [Decimal]
  # @!attribute attack_lightning__7
  #   @return [Decimal]
  # @!attribute attack_lightning__8
  #   @return [Decimal]
  # @!attribute attack_lightning__9
  #   @return [Decimal]
  # @!attribute attack_lightning__10
  #   @return [Decimal]
  # @!attribute attack_lightning__11
  #   @return [Decimal]
  # @!attribute attack_lightning__12
  #   @return [Decimal]
  # @!attribute attack_lightning__13
  #   @return [Decimal]
  # @!attribute attack_lightning__14
  #   @return [Decimal]
  # @!attribute attack_lightning__15
  #   @return [Decimal]
  # @!attribute attack_lightning__16
  #   @return [Decimal]
  # @!attribute attack_lightning__17
  #   @return [Decimal]
  # @!attribute attack_lightning__18
  #   @return [Decimal]
  # @!attribute attack_lightning__19
  #   @return [Decimal]
  # @!attribute attack_lightning__20
  #   @return [Decimal]
  # @!attribute attack_lightning__21
  #   @return [Decimal]
  # @!attribute attack_lightning__22
  #   @return [Decimal]
  # @!attribute attack_lightning__23
  #   @return [Decimal]
  # @!attribute attack_lightning__24
  #   @return [Decimal]
  # @!attribute attack_lightning__25
  #   @return [Decimal]
  # @!attribute attack_holy__0
  #   @return [Decimal]
  # @!attribute attack_holy__1
  #   @return [Decimal]
  # @!attribute attack_holy__2
  #   @return [Decimal]
  # @!attribute attack_holy__3
  #   @return [Decimal]
  # @!attribute attack_holy__4
  #   @return [Decimal]
  # @!attribute attack_holy__5
  #   @return [Decimal]
  # @!attribute attack_holy__6
  #   @return [Decimal]
  # @!attribute attack_holy__7
  #   @return [Decimal]
  # @!attribute attack_holy__8
  #   @return [Decimal]
  # @!attribute attack_holy__9
  #   @return [Decimal]
  # @!attribute attack_holy__10
  #   @return [Decimal]
  # @!attribute attack_holy__11
  #   @return [Decimal]
  # @!attribute attack_holy__12
  #   @return [Decimal]
  # @!attribute attack_holy__13
  #   @return [Decimal]
  # @!attribute attack_holy__14
  #   @return [Decimal]
  # @!attribute attack_holy__15
  #   @return [Decimal]
  # @!attribute attack_holy__16
  #   @return [Decimal]
  # @!attribute attack_holy__17
  #   @return [Decimal]
  # @!attribute attack_holy__18
  #   @return [Decimal]
  # @!attribute attack_holy__19
  #   @return [Decimal]
  # @!attribute attack_holy__20
  #   @return [Decimal]
  # @!attribute attack_holy__21
  #   @return [Decimal]
  # @!attribute attack_holy__22
  #   @return [Decimal]
  # @!attribute attack_holy__23
  #   @return [Decimal]
  # @!attribute attack_holy__24
  #   @return [Decimal]
  # @!attribute attack_holy__25
  #   @return [Decimal]
  # @!attribute attack_stamina__0
  #   @return [Decimal]
  # @!attribute attack_stamina__1
  #   @return [Decimal]
  # @!attribute attack_stamina__2
  #   @return [Decimal]
  # @!attribute attack_stamina__3
  #   @return [Decimal]
  # @!attribute attack_stamina__4
  #   @return [Decimal]
  # @!attribute attack_stamina__5
  #   @return [Decimal]
  # @!attribute attack_stamina__6
  #   @return [Decimal]
  # @!attribute attack_stamina__7
  #   @return [Decimal]
  # @!attribute attack_stamina__8
  #   @return [Decimal]
  # @!attribute attack_stamina__9
  #   @return [Decimal]
  # @!attribute attack_stamina__10
  #   @return [Decimal]
  # @!attribute attack_stamina__11
  #   @return [Decimal]
  # @!attribute attack_stamina__12
  #   @return [Decimal]
  # @!attribute attack_stamina__13
  #   @return [Decimal]
  # @!attribute attack_stamina__14
  #   @return [Decimal]
  # @!attribute attack_stamina__15
  #   @return [Decimal]
  # @!attribute attack_stamina__16
  #   @return [Decimal]
  # @!attribute attack_stamina__17
  #   @return [Decimal]
  # @!attribute attack_stamina__18
  #   @return [Decimal]
  # @!attribute attack_stamina__19
  #   @return [Decimal]
  # @!attribute attack_stamina__20
  #   @return [Decimal]
  # @!attribute attack_stamina__21
  #   @return [Decimal]
  # @!attribute attack_stamina__22
  #   @return [Decimal]
  # @!attribute attack_stamina__23
  #   @return [Decimal]
  # @!attribute attack_stamina__24
  #   @return [Decimal]
  # @!attribute attack_stamina__25
  #   @return [Decimal]

  # @!attribute scaling_strength__0
  #   @return [Decimal]
  # @!attribute scaling_strength__1
  #   @return [Decimal]
  # @!attribute scaling_strength__2
  #   @return [Decimal]
  # @!attribute scaling_strength__3
  #   @return [Decimal]
  # @!attribute scaling_strength__4
  #   @return [Decimal]
  # @!attribute scaling_strength__5
  #   @return [Decimal]
  # @!attribute scaling_strength__6
  #   @return [Decimal]
  # @!attribute scaling_strength__7
  #   @return [Decimal]
  # @!attribute scaling_strength__8
  #   @return [Decimal]
  # @!attribute scaling_strength__9
  #   @return [Decimal]
  # @!attribute scaling_strength__10
  #   @return [Decimal]
  # @!attribute scaling_strength__11
  #   @return [Decimal]
  # @!attribute scaling_strength__12
  #   @return [Decimal]
  # @!attribute scaling_strength__13
  #   @return [Decimal]
  # @!attribute scaling_strength__14
  #   @return [Decimal]
  # @!attribute scaling_strength__15
  #   @return [Decimal]
  # @!attribute scaling_strength__16
  #   @return [Decimal]
  # @!attribute scaling_strength__17
  #   @return [Decimal]
  # @!attribute scaling_strength__18
  #   @return [Decimal]
  # @!attribute scaling_strength__19
  #   @return [Decimal]
  # @!attribute scaling_strength__20
  #   @return [Decimal]
  # @!attribute scaling_strength__21
  #   @return [Decimal]
  # @!attribute scaling_strength__22
  #   @return [Decimal]
  # @!attribute scaling_strength__23
  #   @return [Decimal]
  # @!attribute scaling_strength__24
  #   @return [Decimal]
  # @!attribute scaling_strength__25
  #   @return [Decimal]
  # @!attribute scaling_dexterity__0
  #   @return [Decimal]
  # @!attribute scaling_dexterity__1
  #   @return [Decimal]
  # @!attribute scaling_dexterity__2
  #   @return [Decimal]
  # @!attribute scaling_dexterity__3
  #   @return [Decimal]
  # @!attribute scaling_dexterity__4
  #   @return [Decimal]
  # @!attribute scaling_dexterity__5
  #   @return [Decimal]
  # @!attribute scaling_dexterity__6
  #   @return [Decimal]
  # @!attribute scaling_dexterity__7
  #   @return [Decimal]
  # @!attribute scaling_dexterity__8
  #   @return [Decimal]
  # @!attribute scaling_dexterity__9
  #   @return [Decimal]
  # @!attribute scaling_dexterity__10
  #   @return [Decimal]
  # @!attribute scaling_dexterity__11
  #   @return [Decimal]
  # @!attribute scaling_dexterity__12
  #   @return [Decimal]
  # @!attribute scaling_dexterity__13
  #   @return [Decimal]
  # @!attribute scaling_dexterity__14
  #   @return [Decimal]
  # @!attribute scaling_dexterity__15
  #   @return [Decimal]
  # @!attribute scaling_dexterity__16
  #   @return [Decimal]
  # @!attribute scaling_dexterity__17
  #   @return [Decimal]
  # @!attribute scaling_dexterity__18
  #   @return [Decimal]
  # @!attribute scaling_dexterity__19
  #   @return [Decimal]
  # @!attribute scaling_dexterity__20
  #   @return [Decimal]
  # @!attribute scaling_dexterity__21
  #   @return [Decimal]
  # @!attribute scaling_dexterity__22
  #   @return [Decimal]
  # @!attribute scaling_dexterity__23
  #   @return [Decimal]
  # @!attribute scaling_dexterity__24
  #   @return [Decimal]
  # @!attribute scaling_dexterity__25
  #   @return [Decimal]
  # @!attribute scaling_intelligence__0
  #   @return [Decimal]
  # @!attribute scaling_intelligence__1
  #   @return [Decimal]
  # @!attribute scaling_intelligence__2
  #   @return [Decimal]
  # @!attribute scaling_intelligence__3
  #   @return [Decimal]
  # @!attribute scaling_intelligence__4
  #   @return [Decimal]
  # @!attribute scaling_intelligence__5
  #   @return [Decimal]
  # @!attribute scaling_intelligence__6
  #   @return [Decimal]
  # @!attribute scaling_intelligence__7
  #   @return [Decimal]
  # @!attribute scaling_intelligence__8
  #   @return [Decimal]
  # @!attribute scaling_intelligence__9
  #   @return [Decimal]
  # @!attribute scaling_intelligence__10
  #   @return [Decimal]
  # @!attribute scaling_intelligence__11
  #   @return [Decimal]
  # @!attribute scaling_intelligence__12
  #   @return [Decimal]
  # @!attribute scaling_intelligence__13
  #   @return [Decimal]
  # @!attribute scaling_intelligence__14
  #   @return [Decimal]
  # @!attribute scaling_intelligence__15
  #   @return [Decimal]
  # @!attribute scaling_intelligence__16
  #   @return [Decimal]
  # @!attribute scaling_intelligence__17
  #   @return [Decimal]
  # @!attribute scaling_intelligence__18
  #   @return [Decimal]
  # @!attribute scaling_intelligence__19
  #   @return [Decimal]
  # @!attribute scaling_intelligence__20
  #   @return [Decimal]
  # @!attribute scaling_intelligence__21
  #   @return [Decimal]
  # @!attribute scaling_intelligence__22
  #   @return [Decimal]
  # @!attribute scaling_intelligence__23
  #   @return [Decimal]
  # @!attribute scaling_intelligence__24
  #   @return [Decimal]
  # @!attribute scaling_intelligence__25
  #   @return [Decimal]
  # @!attribute scaling_faith__0
  #   @return [Decimal]
  # @!attribute scaling_faith__1
  #   @return [Decimal]
  # @!attribute scaling_faith__2
  #   @return [Decimal]
  # @!attribute scaling_faith__3
  #   @return [Decimal]
  # @!attribute scaling_faith__4
  #   @return [Decimal]
  # @!attribute scaling_faith__5
  #   @return [Decimal]
  # @!attribute scaling_faith__6
  #   @return [Decimal]
  # @!attribute scaling_faith__7
  #   @return [Decimal]
  # @!attribute scaling_faith__8
  #   @return [Decimal]
  # @!attribute scaling_faith__9
  #   @return [Decimal]
  # @!attribute scaling_faith__10
  #   @return [Decimal]
  # @!attribute scaling_faith__11
  #   @return [Decimal]
  # @!attribute scaling_faith__12
  #   @return [Decimal]
  # @!attribute scaling_faith__13
  #   @return [Decimal]
  # @!attribute scaling_faith__14
  #   @return [Decimal]
  # @!attribute scaling_faith__15
  #   @return [Decimal]
  # @!attribute scaling_faith__16
  #   @return [Decimal]
  # @!attribute scaling_faith__17
  #   @return [Decimal]
  # @!attribute scaling_faith__18
  #   @return [Decimal]
  # @!attribute scaling_faith__19
  #   @return [Decimal]
  # @!attribute scaling_faith__20
  #   @return [Decimal]
  # @!attribute scaling_faith__21
  #   @return [Decimal]
  # @!attribute scaling_faith__22
  #   @return [Decimal]
  # @!attribute scaling_faith__23
  #   @return [Decimal]
  # @!attribute scaling_faith__24
  #   @return [Decimal]
  # @!attribute scaling_faith__25
  #   @return [Decimal]
  # @!attribute scaling_arcane__0
  #   @return [Decimal]
  # @!attribute scaling_arcane__1
  #   @return [Decimal]
  # @!attribute scaling_arcane__2
  #   @return [Decimal]
  # @!attribute scaling_arcane__3
  #   @return [Decimal]
  # @!attribute scaling_arcane__4
  #   @return [Decimal]
  # @!attribute scaling_arcane__5
  #   @return [Decimal]
  # @!attribute scaling_arcane__6
  #   @return [Decimal]
  # @!attribute scaling_arcane__7
  #   @return [Decimal]
  # @!attribute scaling_arcane__8
  #   @return [Decimal]
  # @!attribute scaling_arcane__9
  #   @return [Decimal]
  # @!attribute scaling_arcane__10
  #   @return [Decimal]
  # @!attribute scaling_arcane__11
  #   @return [Decimal]
  # @!attribute scaling_arcane__12
  #   @return [Decimal]
  # @!attribute scaling_arcane__13
  #   @return [Decimal]
  # @!attribute scaling_arcane__14
  #   @return [Decimal]
  # @!attribute scaling_arcane__15
  #   @return [Decimal]
  # @!attribute scaling_arcane__16
  #   @return [Decimal]
  # @!attribute scaling_arcane__17
  #   @return [Decimal]
  # @!attribute scaling_arcane__18
  #   @return [Decimal]
  # @!attribute scaling_arcane__19
  #   @return [Decimal]
  # @!attribute scaling_arcane__20
  #   @return [Decimal]
  # @!attribute scaling_arcane__21
  #   @return [Decimal]
  # @!attribute scaling_arcane__22
  #   @return [Decimal]
  # @!attribute scaling_arcane__23
  #   @return [Decimal]
  # @!attribute scaling_arcane__24
  #   @return [Decimal]
  # @!attribute scaling_arcane__25
  #   @return [Decimal]

  # @!endgroup Attributes

  # ============================================================================
  # Associations
  # ============================================================================

  # @!group Associations

  # @!attribute weapon
  #   @return [Weapon]
  belongs_to(:weapon)

  # @!attribute weapon_affinity
  #   @return [WeaponAffinity]
  belongs_to(:weapon_affinity)

  # @!attribute attack_element_correct_param
  #   @return [AttackElementCorrectParam]
  belongs_to(:attack_element_correct_param)

  # @!endgroup Associations
end
