class WeaponStat < ApplicationRecord

  # ============================================================================
  # Attributes
  # ============================================================================

  # @!group Attributes

  # @!attribute name
  #   @return [String]
  validates(:name, presence: true, uniqueness: true)

  # @!attribute attack_physical_0
  #   @return [Decimal]
  # @!attribute attack_physical_1
  #   @return [Decimal]
  # @!attribute attack_physical_2
  #   @return [Decimal]
  # @!attribute attack_physical_3
  #   @return [Decimal]
  # @!attribute attack_physical_4
  #   @return [Decimal]
  # @!attribute attack_physical_5
  #   @return [Decimal]
  # @!attribute attack_physical_6
  #   @return [Decimal]
  # @!attribute attack_physical_7
  #   @return [Decimal]
  # @!attribute attack_physical_8
  #   @return [Decimal]
  # @!attribute attack_physical_9
  #   @return [Decimal]
  # @!attribute attack_physical_10
  #   @return [Decimal]
  # @!attribute attack_physical_11
  #   @return [Decimal]
  # @!attribute attack_physical_12
  #   @return [Decimal]
  # @!attribute attack_physical_13
  #   @return [Decimal]
  # @!attribute attack_physical_14
  #   @return [Decimal]
  # @!attribute attack_physical_15
  #   @return [Decimal]
  # @!attribute attack_physical_16
  #   @return [Decimal]
  # @!attribute attack_physical_17
  #   @return [Decimal]
  # @!attribute attack_physical_18
  #   @return [Decimal]
  # @!attribute attack_physical_19
  #   @return [Decimal]
  # @!attribute attack_physical_20
  #   @return [Decimal]
  # @!attribute attack_physical_21
  #   @return [Decimal]
  # @!attribute attack_physical_22
  #   @return [Decimal]
  # @!attribute attack_physical_23
  #   @return [Decimal]
  # @!attribute attack_physical_24
  #   @return [Decimal]
  # @!attribute attack_physical_25
  #   @return [Decimal]
  # @!attribute attack_magic_0
  #   @return [Decimal]
  # @!attribute attack_magic_1
  #   @return [Decimal]
  # @!attribute attack_magic_2
  #   @return [Decimal]
  # @!attribute attack_magic_3
  #   @return [Decimal]
  # @!attribute attack_magic_4
  #   @return [Decimal]
  # @!attribute attack_magic_5
  #   @return [Decimal]
  # @!attribute attack_magic_6
  #   @return [Decimal]
  # @!attribute attack_magic_7
  #   @return [Decimal]
  # @!attribute attack_magic_8
  #   @return [Decimal]
  # @!attribute attack_magic_9
  #   @return [Decimal]
  # @!attribute attack_magic_10
  #   @return [Decimal]
  # @!attribute attack_magic_11
  #   @return [Decimal]
  # @!attribute attack_magic_12
  #   @return [Decimal]
  # @!attribute attack_magic_13
  #   @return [Decimal]
  # @!attribute attack_magic_14
  #   @return [Decimal]
  # @!attribute attack_magic_15
  #   @return [Decimal]
  # @!attribute attack_magic_16
  #   @return [Decimal]
  # @!attribute attack_magic_17
  #   @return [Decimal]
  # @!attribute attack_magic_18
  #   @return [Decimal]
  # @!attribute attack_magic_19
  #   @return [Decimal]
  # @!attribute attack_magic_20
  #   @return [Decimal]
  # @!attribute attack_magic_21
  #   @return [Decimal]
  # @!attribute attack_magic_22
  #   @return [Decimal]
  # @!attribute attack_magic_23
  #   @return [Decimal]
  # @!attribute attack_magic_24
  #   @return [Decimal]
  # @!attribute attack_magic_25
  #   @return [Decimal]
  # @!attribute attack_fire_0
  #   @return [Decimal]
  # @!attribute attack_fire_1
  #   @return [Decimal]
  # @!attribute attack_fire_2
  #   @return [Decimal]
  # @!attribute attack_fire_3
  #   @return [Decimal]
  # @!attribute attack_fire_4
  #   @return [Decimal]
  # @!attribute attack_fire_5
  #   @return [Decimal]
  # @!attribute attack_fire_6
  #   @return [Decimal]
  # @!attribute attack_fire_7
  #   @return [Decimal]
  # @!attribute attack_fire_8
  #   @return [Decimal]
  # @!attribute attack_fire_9
  #   @return [Decimal]
  # @!attribute attack_fire_10
  #   @return [Decimal]
  # @!attribute attack_fire_11
  #   @return [Decimal]
  # @!attribute attack_fire_12
  #   @return [Decimal]
  # @!attribute attack_fire_13
  #   @return [Decimal]
  # @!attribute attack_fire_14
  #   @return [Decimal]
  # @!attribute attack_fire_15
  #   @return [Decimal]
  # @!attribute attack_fire_16
  #   @return [Decimal]
  # @!attribute attack_fire_17
  #   @return [Decimal]
  # @!attribute attack_fire_18
  #   @return [Decimal]
  # @!attribute attack_fire_19
  #   @return [Decimal]
  # @!attribute attack_fire_20
  #   @return [Decimal]
  # @!attribute attack_fire_21
  #   @return [Decimal]
  # @!attribute attack_fire_22
  #   @return [Decimal]
  # @!attribute attack_fire_23
  #   @return [Decimal]
  # @!attribute attack_fire_24
  #   @return [Decimal]
  # @!attribute attack_fire_25
  #   @return [Decimal]
  # @!attribute attack_lightning_0
  #   @return [Decimal]
  # @!attribute attack_lightning_1
  #   @return [Decimal]
  # @!attribute attack_lightning_2
  #   @return [Decimal]
  # @!attribute attack_lightning_3
  #   @return [Decimal]
  # @!attribute attack_lightning_4
  #   @return [Decimal]
  # @!attribute attack_lightning_5
  #   @return [Decimal]
  # @!attribute attack_lightning_6
  #   @return [Decimal]
  # @!attribute attack_lightning_7
  #   @return [Decimal]
  # @!attribute attack_lightning_8
  #   @return [Decimal]
  # @!attribute attack_lightning_9
  #   @return [Decimal]
  # @!attribute attack_lightning_10
  #   @return [Decimal]
  # @!attribute attack_lightning_11
  #   @return [Decimal]
  # @!attribute attack_lightning_12
  #   @return [Decimal]
  # @!attribute attack_lightning_13
  #   @return [Decimal]
  # @!attribute attack_lightning_14
  #   @return [Decimal]
  # @!attribute attack_lightning_15
  #   @return [Decimal]
  # @!attribute attack_lightning_16
  #   @return [Decimal]
  # @!attribute attack_lightning_17
  #   @return [Decimal]
  # @!attribute attack_lightning_18
  #   @return [Decimal]
  # @!attribute attack_lightning_19
  #   @return [Decimal]
  # @!attribute attack_lightning_20
  #   @return [Decimal]
  # @!attribute attack_lightning_21
  #   @return [Decimal]
  # @!attribute attack_lightning_22
  #   @return [Decimal]
  # @!attribute attack_lightning_23
  #   @return [Decimal]
  # @!attribute attack_lightning_24
  #   @return [Decimal]
  # @!attribute attack_lightning_25
  #   @return [Decimal]
  # @!attribute attack_holy_0
  #   @return [Decimal]
  # @!attribute attack_holy_1
  #   @return [Decimal]
  # @!attribute attack_holy_2
  #   @return [Decimal]
  # @!attribute attack_holy_3
  #   @return [Decimal]
  # @!attribute attack_holy_4
  #   @return [Decimal]
  # @!attribute attack_holy_5
  #   @return [Decimal]
  # @!attribute attack_holy_6
  #   @return [Decimal]
  # @!attribute attack_holy_7
  #   @return [Decimal]
  # @!attribute attack_holy_8
  #   @return [Decimal]
  # @!attribute attack_holy_9
  #   @return [Decimal]
  # @!attribute attack_holy_10
  #   @return [Decimal]
  # @!attribute attack_holy_11
  #   @return [Decimal]
  # @!attribute attack_holy_12
  #   @return [Decimal]
  # @!attribute attack_holy_13
  #   @return [Decimal]
  # @!attribute attack_holy_14
  #   @return [Decimal]
  # @!attribute attack_holy_15
  #   @return [Decimal]
  # @!attribute attack_holy_16
  #   @return [Decimal]
  # @!attribute attack_holy_17
  #   @return [Decimal]
  # @!attribute attack_holy_18
  #   @return [Decimal]
  # @!attribute attack_holy_19
  #   @return [Decimal]
  # @!attribute attack_holy_20
  #   @return [Decimal]
  # @!attribute attack_holy_21
  #   @return [Decimal]
  # @!attribute attack_holy_22
  #   @return [Decimal]
  # @!attribute attack_holy_23
  #   @return [Decimal]
  # @!attribute attack_holy_24
  #   @return [Decimal]
  # @!attribute attack_holy_25
  #   @return [Decimal]
  # @!attribute attack_stamina_0
  #   @return [Decimal]
  # @!attribute attack_stamina_1
  #   @return [Decimal]
  # @!attribute attack_stamina_2
  #   @return [Decimal]
  # @!attribute attack_stamina_3
  #   @return [Decimal]
  # @!attribute attack_stamina_4
  #   @return [Decimal]
  # @!attribute attack_stamina_5
  #   @return [Decimal]
  # @!attribute attack_stamina_6
  #   @return [Decimal]
  # @!attribute attack_stamina_7
  #   @return [Decimal]
  # @!attribute attack_stamina_8
  #   @return [Decimal]
  # @!attribute attack_stamina_9
  #   @return [Decimal]
  # @!attribute attack_stamina_10
  #   @return [Decimal]
  # @!attribute attack_stamina_11
  #   @return [Decimal]
  # @!attribute attack_stamina_12
  #   @return [Decimal]
  # @!attribute attack_stamina_13
  #   @return [Decimal]
  # @!attribute attack_stamina_14
  #   @return [Decimal]
  # @!attribute attack_stamina_15
  #   @return [Decimal]
  # @!attribute attack_stamina_16
  #   @return [Decimal]
  # @!attribute attack_stamina_17
  #   @return [Decimal]
  # @!attribute attack_stamina_18
  #   @return [Decimal]
  # @!attribute attack_stamina_19
  #   @return [Decimal]
  # @!attribute attack_stamina_20
  #   @return [Decimal]
  # @!attribute attack_stamina_21
  #   @return [Decimal]
  # @!attribute attack_stamina_22
  #   @return [Decimal]
  # @!attribute attack_stamina_23
  #   @return [Decimal]
  # @!attribute attack_stamina_24
  #   @return [Decimal]
  # @!attribute attack_stamina_25
  #   @return [Decimal]

  # @!attribute scaling_strength_0
  #   @return [Decimal]
  # @!attribute scaling_strength_1
  #   @return [Decimal]
  # @!attribute scaling_strength_2
  #   @return [Decimal]
  # @!attribute scaling_strength_3
  #   @return [Decimal]
  # @!attribute scaling_strength_4
  #   @return [Decimal]
  # @!attribute scaling_strength_5
  #   @return [Decimal]
  # @!attribute scaling_strength_6
  #   @return [Decimal]
  # @!attribute scaling_strength_7
  #   @return [Decimal]
  # @!attribute scaling_strength_8
  #   @return [Decimal]
  # @!attribute scaling_strength_9
  #   @return [Decimal]
  # @!attribute scaling_strength_10
  #   @return [Decimal]
  # @!attribute scaling_strength_11
  #   @return [Decimal]
  # @!attribute scaling_strength_12
  #   @return [Decimal]
  # @!attribute scaling_strength_13
  #   @return [Decimal]
  # @!attribute scaling_strength_14
  #   @return [Decimal]
  # @!attribute scaling_strength_15
  #   @return [Decimal]
  # @!attribute scaling_strength_16
  #   @return [Decimal]
  # @!attribute scaling_strength_17
  #   @return [Decimal]
  # @!attribute scaling_strength_18
  #   @return [Decimal]
  # @!attribute scaling_strength_19
  #   @return [Decimal]
  # @!attribute scaling_strength_20
  #   @return [Decimal]
  # @!attribute scaling_strength_21
  #   @return [Decimal]
  # @!attribute scaling_strength_22
  #   @return [Decimal]
  # @!attribute scaling_strength_23
  #   @return [Decimal]
  # @!attribute scaling_strength_24
  #   @return [Decimal]
  # @!attribute scaling_strength_25
  #   @return [Decimal]
  # @!attribute scaling_dexterity_0
  #   @return [Decimal]
  # @!attribute scaling_dexterity_1
  #   @return [Decimal]
  # @!attribute scaling_dexterity_2
  #   @return [Decimal]
  # @!attribute scaling_dexterity_3
  #   @return [Decimal]
  # @!attribute scaling_dexterity_4
  #   @return [Decimal]
  # @!attribute scaling_dexterity_5
  #   @return [Decimal]
  # @!attribute scaling_dexterity_6
  #   @return [Decimal]
  # @!attribute scaling_dexterity_7
  #   @return [Decimal]
  # @!attribute scaling_dexterity_8
  #   @return [Decimal]
  # @!attribute scaling_dexterity_9
  #   @return [Decimal]
  # @!attribute scaling_dexterity_10
  #   @return [Decimal]
  # @!attribute scaling_dexterity_11
  #   @return [Decimal]
  # @!attribute scaling_dexterity_12
  #   @return [Decimal]
  # @!attribute scaling_dexterity_13
  #   @return [Decimal]
  # @!attribute scaling_dexterity_14
  #   @return [Decimal]
  # @!attribute scaling_dexterity_15
  #   @return [Decimal]
  # @!attribute scaling_dexterity_16
  #   @return [Decimal]
  # @!attribute scaling_dexterity_17
  #   @return [Decimal]
  # @!attribute scaling_dexterity_18
  #   @return [Decimal]
  # @!attribute scaling_dexterity_19
  #   @return [Decimal]
  # @!attribute scaling_dexterity_20
  #   @return [Decimal]
  # @!attribute scaling_dexterity_21
  #   @return [Decimal]
  # @!attribute scaling_dexterity_22
  #   @return [Decimal]
  # @!attribute scaling_dexterity_23
  #   @return [Decimal]
  # @!attribute scaling_dexterity_24
  #   @return [Decimal]
  # @!attribute scaling_dexterity_25
  #   @return [Decimal]
  # @!attribute scaling_intelligence_0
  #   @return [Decimal]
  # @!attribute scaling_intelligence_1
  #   @return [Decimal]
  # @!attribute scaling_intelligence_2
  #   @return [Decimal]
  # @!attribute scaling_intelligence_3
  #   @return [Decimal]
  # @!attribute scaling_intelligence_4
  #   @return [Decimal]
  # @!attribute scaling_intelligence_5
  #   @return [Decimal]
  # @!attribute scaling_intelligence_6
  #   @return [Decimal]
  # @!attribute scaling_intelligence_7
  #   @return [Decimal]
  # @!attribute scaling_intelligence_8
  #   @return [Decimal]
  # @!attribute scaling_intelligence_9
  #   @return [Decimal]
  # @!attribute scaling_intelligence_10
  #   @return [Decimal]
  # @!attribute scaling_intelligence_11
  #   @return [Decimal]
  # @!attribute scaling_intelligence_12
  #   @return [Decimal]
  # @!attribute scaling_intelligence_13
  #   @return [Decimal]
  # @!attribute scaling_intelligence_14
  #   @return [Decimal]
  # @!attribute scaling_intelligence_15
  #   @return [Decimal]
  # @!attribute scaling_intelligence_16
  #   @return [Decimal]
  # @!attribute scaling_intelligence_17
  #   @return [Decimal]
  # @!attribute scaling_intelligence_18
  #   @return [Decimal]
  # @!attribute scaling_intelligence_19
  #   @return [Decimal]
  # @!attribute scaling_intelligence_20
  #   @return [Decimal]
  # @!attribute scaling_intelligence_21
  #   @return [Decimal]
  # @!attribute scaling_intelligence_22
  #   @return [Decimal]
  # @!attribute scaling_intelligence_23
  #   @return [Decimal]
  # @!attribute scaling_intelligence_24
  #   @return [Decimal]
  # @!attribute scaling_intelligence_25
  #   @return [Decimal]
  # @!attribute scaling_faith_0
  #   @return [Decimal]
  # @!attribute scaling_faith_1
  #   @return [Decimal]
  # @!attribute scaling_faith_2
  #   @return [Decimal]
  # @!attribute scaling_faith_3
  #   @return [Decimal]
  # @!attribute scaling_faith_4
  #   @return [Decimal]
  # @!attribute scaling_faith_5
  #   @return [Decimal]
  # @!attribute scaling_faith_6
  #   @return [Decimal]
  # @!attribute scaling_faith_7
  #   @return [Decimal]
  # @!attribute scaling_faith_8
  #   @return [Decimal]
  # @!attribute scaling_faith_9
  #   @return [Decimal]
  # @!attribute scaling_faith_10
  #   @return [Decimal]
  # @!attribute scaling_faith_11
  #   @return [Decimal]
  # @!attribute scaling_faith_12
  #   @return [Decimal]
  # @!attribute scaling_faith_13
  #   @return [Decimal]
  # @!attribute scaling_faith_14
  #   @return [Decimal]
  # @!attribute scaling_faith_15
  #   @return [Decimal]
  # @!attribute scaling_faith_16
  #   @return [Decimal]
  # @!attribute scaling_faith_17
  #   @return [Decimal]
  # @!attribute scaling_faith_18
  #   @return [Decimal]
  # @!attribute scaling_faith_19
  #   @return [Decimal]
  # @!attribute scaling_faith_20
  #   @return [Decimal]
  # @!attribute scaling_faith_21
  #   @return [Decimal]
  # @!attribute scaling_faith_22
  #   @return [Decimal]
  # @!attribute scaling_faith_23
  #   @return [Decimal]
  # @!attribute scaling_faith_24
  #   @return [Decimal]
  # @!attribute scaling_faith_25
  #   @return [Decimal]
  # @!attribute scaling_arcane_0
  #   @return [Decimal]
  # @!attribute scaling_arcane_1
  #   @return [Decimal]
  # @!attribute scaling_arcane_2
  #   @return [Decimal]
  # @!attribute scaling_arcane_3
  #   @return [Decimal]
  # @!attribute scaling_arcane_4
  #   @return [Decimal]
  # @!attribute scaling_arcane_5
  #   @return [Decimal]
  # @!attribute scaling_arcane_6
  #   @return [Decimal]
  # @!attribute scaling_arcane_7
  #   @return [Decimal]
  # @!attribute scaling_arcane_8
  #   @return [Decimal]
  # @!attribute scaling_arcane_9
  #   @return [Decimal]
  # @!attribute scaling_arcane_10
  #   @return [Decimal]
  # @!attribute scaling_arcane_11
  #   @return [Decimal]
  # @!attribute scaling_arcane_12
  #   @return [Decimal]
  # @!attribute scaling_arcane_13
  #   @return [Decimal]
  # @!attribute scaling_arcane_14
  #   @return [Decimal]
  # @!attribute scaling_arcane_15
  #   @return [Decimal]
  # @!attribute scaling_arcane_16
  #   @return [Decimal]
  # @!attribute scaling_arcane_17
  #   @return [Decimal]
  # @!attribute scaling_arcane_18
  #   @return [Decimal]
  # @!attribute scaling_arcane_19
  #   @return [Decimal]
  # @!attribute scaling_arcane_20
  #   @return [Decimal]
  # @!attribute scaling_arcane_21
  #   @return [Decimal]
  # @!attribute scaling_arcane_22
  #   @return [Decimal]
  # @!attribute scaling_arcane_23
  #   @return [Decimal]
  # @!attribute scaling_arcane_24
  #   @return [Decimal]
  # @!attribute scaling_arcane_25
  #   @return [Decimal]

  # @!endgroup Attributes

  # ============================================================================
  # Associations
  # ============================================================================

  # @!group Associations

  # @!attribute weapon
  #   @return [Weapon]
  belongs_to(:weapon)

  # @!attribute weapon_affinity
  #   @return [WeaponAffinity]
  belongs_to(:weapon_affinity)

  # @!attribute attack_element_correct_param
  #   @return [AttackElementCorrectParam]
  belongs_to(:attack_element_correct_param)

  # @!endgroup Associations
end
