export interface WeaponScalingStatData {
    strength__00: number
    strength__01: number
    strength__02: number
    strength__03: number
    strength__04: number
    strength__05: number
    strength__06: number
    strength__07: number
    strength__08: number
    strength__09: number
    strength__10: number
    strength__11: number
    strength__12: number
    strength__13: number
    strength__14: number
    strength__15: number
    strength__16: number
    strength__17: number
    strength__18: number
    strength__19: number
    strength__20: number
    strength__21: number
    strength__22: number
    strength__23: number
    strength__24: number
    strength__25: number
    dexterity__00: number
    dexterity__01: number
    dexterity__02: number
    dexterity__03: number
    dexterity__04: number
    dexterity__05: number
    dexterity__06: number
    dexterity__07: number
    dexterity__08: number
    dexterity__09: number
    dexterity__10: number
    dexterity__11: number
    dexterity__12: number
    dexterity__13: number
    dexterity__14: number
    dexterity__15: number
    dexterity__16: number
    dexterity__17: number
    dexterity__18: number
    dexterity__19: number
    dexterity__20: number
    dexterity__21: number
    dexterity__22: number
    dexterity__23: number
    dexterity__24: number
    dexterity__25: number
    intelligence__00: number
    intelligence__01: number
    intelligence__02: number
    intelligence__03: number
    intelligence__04: number
    intelligence__05: number
    intelligence__06: number
    intelligence__07: number
    intelligence__08: number
    intelligence__09: number
    intelligence__10: number
    intelligence__11: number
    intelligence__12: number
    intelligence__13: number
    intelligence__14: number
    intelligence__15: number
    intelligence__16: number
    intelligence__17: number
    intelligence__18: number
    intelligence__19: number
    intelligence__20: number
    intelligence__21: number
    intelligence__22: number
    intelligence__23: number
    intelligence__24: number
    intelligence__25: number
    faith__00: number
    faith__01: number
    faith__02: number
    faith__03: number
    faith__04: number
    faith__05: number
    faith__06: number
    faith__07: number
    faith__08: number
    faith__09: number
    faith__10: number
    faith__11: number
    faith__12: number
    faith__13: number
    faith__14: number
    faith__15: number
    faith__16: number
    faith__17: number
    faith__18: number
    faith__19: number
    faith__20: number
    faith__21: number
    faith__22: number
    faith__23: number
    faith__24: number
    faith__25: number
    arcane__00: number
    arcane__01: number
    arcane__02: number
    arcane__03: number
    arcane__04: number
    arcane__05: number
    arcane__06: number
    arcane__07: number
    arcane__08: number
    arcane__09: number
    arcane__10: number
    arcane__11: number
    arcane__12: number
    arcane__13: number
    arcane__14: number
    arcane__15: number
    arcane__16: number
    arcane__17: number
    arcane__18: number
    arcane__19: number
    arcane__20: number
    arcane__21: number
    arcane__22: number
    arcane__23: number
    arcane__24: number
    arcane__25: number
}
