export interface WeaponAttackStat {

    name: string
    weapon_id: number
    weapon_affinity_id: number

    physical__00: number
    physical__01: number
    physical__02: number
    physical__03: number
    physical__04: number
    physical__05: number
    physical__06: number
    physical__07: number
    physical__08: number
    physical__09: number
    physical__10: number
    physical__11: number
    physical__12: number
    physical__13: number
    physical__14: number
    physical__15: number
    physical__16: number
    physical__17: number
    physical__18: number
    physical__19: number
    physical__20: number
    physical__21: number
    physical__22: number
    physical__23: number
    physical__24: number
    physical__25: number
    magic__00: number
    magic__01: number
    magic__02: number
    magic__03: number
    magic__04: number
    magic__05: number
    magic__06: number
    magic__07: number
    magic__08: number
    magic__09: number
    magic__10: number
    magic__11: number
    magic__12: number
    magic__13: number
    magic__14: number
    magic__15: number
    magic__16: number
    magic__17: number
    magic__18: number
    magic__19: number
    magic__20: number
    magic__21: number
    magic__22: number
    magic__23: number
    magic__24: number
    magic__25: number
    fire__00: number
    fire__01: number
    fire__02: number
    fire__03: number
    fire__04: number
    fire__05: number
    fire__06: number
    fire__07: number
    fire__08: number
    fire__09: number
    fire__10: number
    fire__11: number
    fire__12: number
    fire__13: number
    fire__14: number
    fire__15: number
    fire__16: number
    fire__17: number
    fire__18: number
    fire__19: number
    fire__20: number
    fire__21: number
    fire__22: number
    fire__23: number
    fire__24: number
    fire__25: number
    lightning__00: number
    lightning__01: number
    lightning__02: number
    lightning__03: number
    lightning__04: number
    lightning__05: number
    lightning__06: number
    lightning__07: number
    lightning__08: number
    lightning__09: number
    lightning__10: number
    lightning__11: number
    lightning__12: number
    lightning__13: number
    lightning__14: number
    lightning__15: number
    lightning__16: number
    lightning__17: number
    lightning__18: number
    lightning__19: number
    lightning__20: number
    lightning__21: number
    lightning__22: number
    lightning__23: number
    lightning__24: number
    lightning__25: number
    holy__00: number
    holy__01: number
    holy__02: number
    holy__03: number
    holy__04: number
    holy__05: number
    holy__06: number
    holy__07: number
    holy__08: number
    holy__09: number
    holy__10: number
    holy__11: number
    holy__12: number
    holy__13: number
    holy__14: number
    holy__15: number
    holy__16: number
    holy__17: number
    holy__18: number
    holy__19: number
    holy__20: number
    holy__21: number
    holy__22: number
    holy__23: number
    holy__24: number
    holy__25: number
    stamina__00: number
    stamina__01: number
    stamina__02: number
    stamina__03: number
    stamina__04: number
    stamina__05: number
    stamina__06: number
    stamina__07: number
    stamina__08: number
    stamina__09: number
    stamina__10: number
    stamina__11: number
    stamina__12: number
    stamina__13: number
    stamina__14: number
    stamina__15: number
    stamina__16: number
    stamina__17: number
    stamina__18: number
    stamina__19: number
    stamina__20: number
    stamina__21: number
    stamina__22: number
    stamina__23: number
    stamina__24: number
    stamina__25: number
}
