export interface WeaponStatData {

    attack_physical_0: number
    attack_physical_1: number
    attack_physical_2: number
    attack_physical_3: number
    attack_physical_4: number
    attack_physical_5: number
    attack_physical_6: number
    attack_physical_7: number
    attack_physical_8: number
    attack_physical_9: number
    attack_physical_10: number
    attack_physical_11: number
    attack_physical_12: number
    attack_physical_13: number
    attack_physical_14: number
    attack_physical_15: number
    attack_physical_16: number
    attack_physical_17: number
    attack_physical_18: number
    attack_physical_19: number
    attack_physical_20: number
    attack_physical_21: number
    attack_physical_22: number
    attack_physical_23: number
    attack_physical_24: number
    attack_physical_25: number
    attack_magic_0: number
    attack_magic_1: number
    attack_magic_2: number
    attack_magic_3: number
    attack_magic_4: number
    attack_magic_5: number
    attack_magic_6: number
    attack_magic_7: number
    attack_magic_8: number
    attack_magic_9: number
    attack_magic_10: number
    attack_magic_11: number
    attack_magic_12: number
    attack_magic_13: number
    attack_magic_14: number
    attack_magic_15: number
    attack_magic_16: number
    attack_magic_17: number
    attack_magic_18: number
    attack_magic_19: number
    attack_magic_20: number
    attack_magic_21: number
    attack_magic_22: number
    attack_magic_23: number
    attack_magic_24: number
    attack_magic_25: number
    attack_fire_0: number
    attack_fire_1: number
    attack_fire_2: number
    attack_fire_3: number
    attack_fire_4: number
    attack_fire_5: number
    attack_fire_6: number
    attack_fire_7: number
    attack_fire_8: number
    attack_fire_9: number
    attack_fire_10: number
    attack_fire_11: number
    attack_fire_12: number
    attack_fire_13: number
    attack_fire_14: number
    attack_fire_15: number
    attack_fire_16: number
    attack_fire_17: number
    attack_fire_18: number
    attack_fire_19: number
    attack_fire_20: number
    attack_fire_21: number
    attack_fire_22: number
    attack_fire_23: number
    attack_fire_24: number
    attack_fire_25: number
    attack_lightning_0: number
    attack_lightning_1: number
    attack_lightning_2: number
    attack_lightning_3: number
    attack_lightning_4: number
    attack_lightning_5: number
    attack_lightning_6: number
    attack_lightning_7: number
    attack_lightning_8: number
    attack_lightning_9: number
    attack_lightning_10: number
    attack_lightning_11: number
    attack_lightning_12: number
    attack_lightning_13: number
    attack_lightning_14: number
    attack_lightning_15: number
    attack_lightning_16: number
    attack_lightning_17: number
    attack_lightning_18: number
    attack_lightning_19: number
    attack_lightning_20: number
    attack_lightning_21: number
    attack_lightning_22: number
    attack_lightning_23: number
    attack_lightning_24: number
    attack_lightning_25: number
    attack_holy_0: number
    attack_holy_1: number
    attack_holy_2: number
    attack_holy_3: number
    attack_holy_4: number
    attack_holy_5: number
    attack_holy_6: number
    attack_holy_7: number
    attack_holy_8: number
    attack_holy_9: number
    attack_holy_10: number
    attack_holy_11: number
    attack_holy_12: number
    attack_holy_13: number
    attack_holy_14: number
    attack_holy_15: number
    attack_holy_16: number
    attack_holy_17: number
    attack_holy_18: number
    attack_holy_19: number
    attack_holy_20: number
    attack_holy_21: number
    attack_holy_22: number
    attack_holy_23: number
    attack_holy_24: number
    attack_holy_25: number
    attack_stamina_0: number
    attack_stamina_1: number
    attack_stamina_2: number
    attack_stamina_3: number
    attack_stamina_4: number
    attack_stamina_5: number
    attack_stamina_6: number
    attack_stamina_7: number
    attack_stamina_8: number
    attack_stamina_9: number
    attack_stamina_10: number
    attack_stamina_11: number
    attack_stamina_12: number
    attack_stamina_13: number
    attack_stamina_14: number
    attack_stamina_15: number
    attack_stamina_16: number
    attack_stamina_17: number
    attack_stamina_18: number
    attack_stamina_19: number
    attack_stamina_20: number
    attack_stamina_21: number
    attack_stamina_22: number
    attack_stamina_23: number
    attack_stamina_24: number
    attack_stamina_25: number

    scaling_strength_0: number
    scaling_strength_1: number
    scaling_strength_2: number
    scaling_strength_3: number
    scaling_strength_4: number
    scaling_strength_5: number
    scaling_strength_6: number
    scaling_strength_7: number
    scaling_strength_8: number
    scaling_strength_9: number
    scaling_strength_10: number
    scaling_strength_11: number
    scaling_strength_12: number
    scaling_strength_13: number
    scaling_strength_14: number
    scaling_strength_15: number
    scaling_strength_16: number
    scaling_strength_17: number
    scaling_strength_18: number
    scaling_strength_19: number
    scaling_strength_20: number
    scaling_strength_21: number
    scaling_strength_22: number
    scaling_strength_23: number
    scaling_strength_24: number
    scaling_strength_25: number
    scaling_dexterity_0: number
    scaling_dexterity_1: number
    scaling_dexterity_2: number
    scaling_dexterity_3: number
    scaling_dexterity_4: number
    scaling_dexterity_5: number
    scaling_dexterity_6: number
    scaling_dexterity_7: number
    scaling_dexterity_8: number
    scaling_dexterity_9: number
    scaling_dexterity_10: number
    scaling_dexterity_11: number
    scaling_dexterity_12: number
    scaling_dexterity_13: number
    scaling_dexterity_14: number
    scaling_dexterity_15: number
    scaling_dexterity_16: number
    scaling_dexterity_17: number
    scaling_dexterity_18: number
    scaling_dexterity_19: number
    scaling_dexterity_20: number
    scaling_dexterity_21: number
    scaling_dexterity_22: number
    scaling_dexterity_23: number
    scaling_dexterity_24: number
    scaling_dexterity_25: number
    scaling_intelligence_0: number
    scaling_intelligence_1: number
    scaling_intelligence_2: number
    scaling_intelligence_3: number
    scaling_intelligence_4: number
    scaling_intelligence_5: number
    scaling_intelligence_6: number
    scaling_intelligence_7: number
    scaling_intelligence_8: number
    scaling_intelligence_9: number
    scaling_intelligence_10: number
    scaling_intelligence_11: number
    scaling_intelligence_12: number
    scaling_intelligence_13: number
    scaling_intelligence_14: number
    scaling_intelligence_15: number
    scaling_intelligence_16: number
    scaling_intelligence_17: number
    scaling_intelligence_18: number
    scaling_intelligence_19: number
    scaling_intelligence_20: number
    scaling_intelligence_21: number
    scaling_intelligence_22: number
    scaling_intelligence_23: number
    scaling_intelligence_24: number
    scaling_intelligence_25: number
    scaling_faith_0: number
    scaling_faith_1: number
    scaling_faith_2: number
    scaling_faith_3: number
    scaling_faith_4: number
    scaling_faith_5: number
    scaling_faith_6: number
    scaling_faith_7: number
    scaling_faith_8: number
    scaling_faith_9: number
    scaling_faith_10: number
    scaling_faith_11: number
    scaling_faith_12: number
    scaling_faith_13: number
    scaling_faith_14: number
    scaling_faith_15: number
    scaling_faith_16: number
    scaling_faith_17: number
    scaling_faith_18: number
    scaling_faith_19: number
    scaling_faith_20: number
    scaling_faith_21: number
    scaling_faith_22: number
    scaling_faith_23: number
    scaling_faith_24: number
    scaling_faith_25: number
    scaling_arcane_0: number
    scaling_arcane_1: number
    scaling_arcane_2: number
    scaling_arcane_3: number
    scaling_arcane_4: number
    scaling_arcane_5: number
    scaling_arcane_6: number
    scaling_arcane_7: number
    scaling_arcane_8: number
    scaling_arcane_9: number
    scaling_arcane_10: number
    scaling_arcane_11: number
    scaling_arcane_12: number
    scaling_arcane_13: number
    scaling_arcane_14: number
    scaling_arcane_15: number
    scaling_arcane_16: number
    scaling_arcane_17: number
    scaling_arcane_18: number
    scaling_arcane_19: number
    scaling_arcane_20: number
    scaling_arcane_21: number
    scaling_arcane_22: number
    scaling_arcane_23: number
    scaling_arcane_24: number
    scaling_arcane_25: number

    passive_type_1: string
    passive_type_2: string

    passive_scarlet_rot_0: Integer
    passive_madness_0: Integer
    passive_sleep_0: Integer
    passive_frost_0: Integer
    passive_poison_0: Integer
    passive_blood_loss_0: Integer
    passive_frost_1: Integer
    passive_poison_1: Integer
    passive_blood_loss_1: Integer
    passive_frost_2: Integer
    passive_poison_2: Integer
    passive_blood_loss_2: Integer
    passive_frost_3: Integer
    passive_poison_3: Integer
    passive_blood_loss_3: Integer
    passive_frost_4: Integer
    passive_poison_4: Integer
    passive_blood_loss_4: Integer
    passive_frost_5: Integer
    passive_poison_5: Integer
    passive_blood_loss_5: Integer
    passive_frost_6: Integer
    passive_poison_6: Integer
    passive_blood_loss_6: Integer
    passive_frost_7: Integer
    passive_poison_7: Integer
    passive_blood_loss_7: Integer
    passive_frost_8: Integer
    passive_poison_8: Integer
    passive_blood_loss_8: Integer
    passive_frost_9: Integer
    passive_poison_9: Integer
    passive_blood_loss_9: Integer
    passive_frost_10: Integer
    passive_poison_10: Integer
    passive_blood_loss_10: Integer
    passive_frost_11: Integer
    passive_poison_11: Integer
    passive_blood_loss_11: Integer
    passive_frost_12: Integer
    passive_poison_12: Integer
    passive_blood_loss_12: Integer
    passive_frost_13: Integer
    passive_poison_13: Integer
    passive_blood_loss_13: Integer
    passive_frost_14: Integer
    passive_poison_14: Integer
    passive_blood_loss_14: Integer
    passive_frost_15: Integer
    passive_poison_15: Integer
    passive_blood_loss_15: Integer
    passive_frost_16: Integer
    passive_poison_16: Integer
    passive_blood_loss_16: Integer
    passive_frost_17: Integer
    passive_poison_17: Integer
    passive_blood_loss_17: Integer
    passive_frost_18: Integer
    passive_poison_18: Integer
    passive_blood_loss_18: Integer
    passive_frost_19: Integer
    passive_poison_19: Integer
    passive_blood_loss_19: Integer
    passive_frost_20: Integer
    passive_poison_20: Integer
    passive_blood_loss_20: Integer
    passive_frost_21: Integer
    passive_poison_21: Integer
    passive_blood_loss_21: Integer
    passive_frost_22: Integer
    passive_poison_22: Integer
    passive_blood_loss_22: Integer
    passive_frost_23: Integer
    passive_poison_23: Integer
    passive_blood_loss_23: Integer
    passive_frost_24: Integer
    passive_poison_24: Integer
    passive_blood_loss_24: Integer
    passive_frost_25: Integer
    passive_poison_25: Integer
    passive_blood_loss_25: Integer
}
